### ISSUE TITLE
Login Module Control flag not specified in JAAS config

### ISSUE THREAD

**Issue by mattia-crypto** [provectus/kafka-ui#1676]
**Describe the bug**
I am deploying kafka-ui via `helmfile`, and I am attempting to connect via `SCRAM_PLAINTEXT` using the below config. My `Pod` starts, however, I see this error:

```
2022-02-24 17:15:09,885 ERROR [parallel-1] c.p.k.u.s.MetricsService: Failed to collect cluster kafka-cluster info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster kafka-cluster
	at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:44)
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3732)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.Operators.error(Operators.java:198)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:135)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4384)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:540)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:134)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
	at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$2(AdminClientServiceImpl.java:40)
	at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:86)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)
	... 16 common frames omitted
Caused by: java.lang.IllegalArgumentException: Login module control flag not specified in JAAS config
	at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:110)
	at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63)
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:88)
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:82)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:167)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:513)
	... 21 common frames omitted
2022-02-24 17:15:09,885 DEBUG [parallel-1] c.p.k.u.s.ClustersMetricsScheduler: Metrics updated for cluster: kafka-cluster
2022-02-24 17:15:39,883 DEBUG [parallel-1] c.p.k.u.s.ClustersMetricsScheduler: Start getting metrics for kafkaCluster: kafka-cluster
2022-02-24 17:15:39,884 INFO  [parallel-1] o.a.k.c.a.AdminClientConfig: AdminClientConfig values: 
```

**Set up**
I use the Strimzi Operator for Kafka to create a cluster with the following configuration, note that it uses SASL_SSL:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    # image: ""
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
        authentication:
          type: scram-sha-512
   authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.1"
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
    rack:
      topologyKey: topology.kubernetes.io/zone
   storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: true
    template:
      pod:
        tolerations:
        - key: kubernetes.monacohq.com/role
          operator: Equal
          value: kafka
          effect: NoSchedule
```

My `kafka-ui` looks like this:

```
releases:

  - name: kafka-ui
    chart: kafka-ui/kafka-ui
    namespace: kafka
    values:
      - existingSecret: "kafka-ui-user" 
      - envs:
          config:
            KAFKA_CLUSTERS_0_NAME:
              "kafka-cluster"
            KAFKA_CLUSTERS_0_ZOOKEEPER:
              "kafka-cluster-zookeeper-client:2181"
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS:
              "kafka-cluster-kafka-bootstrap:9092" # :9093 for TLS
            KAFKA_CLUSTERS_0_READONLY:
              "true"
            KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL:
              "SASL_PLAINTEXT"
            KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM:
              "SCRAM-SHA-512"
            KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG:
              $sasl.jaas.config
```

I pass in `$sasl.jaas.config` in this way because I use a `Secret` with the `password` and `sasl.jaas.config` accordingly. This is passed in correctly.

**Steps to Reproduce**

1. Create an EKS cluster in AWS.
2. Deploy a Strimzi Kafka Operator
3. Create a Strimzi Kafka resource (in example a KafkaCluster CRD)
4. Create a KafkaUser with SCRAM-SHA-512 authentication type
5. Deploy the Kube UI 

**Expected behavior**

I am expecting `kafka-ui` to connect to my brokers.

**Screenshots**

**Additional context**

Not sure whether this is Kafka configuration related, or Kafka-ui configuration related. Anywhay, here is the `AdminClientConfig`:

```
        bootstrap.servers = [kafka-cluster-kafka-bootstrap:9092]
	client.dns.lookup = use_all_dns_ips
	client.id = 
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
        retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = SCRAM-SHA-512
	security.protocol = SASL_PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
```

**Comment by Haarolean** [comment]
Hi, the problem is in `$sasl.jaas.config` variable. There's just no way to output such a variable in bash, with or without escaping. You have to reference it some other way without dots.

**Comment by ddezoysa** [comment]
@mattia-crypto How did you managed to use Strimzi TLS Simple Auth with Kafka-UI? Can you please post an example?

**Comment by SuitableProduce** [comment]
@ddezoysa ,  @mattia-crypto I'd be interested to know as well!
