### ISSUE TITLE
Deployment in Cloud Foundry [Error while creating AdminClient for Cluster Default]

### ISSUE THREAD

**Issue by Thilaknath** [provectus/kafka-ui#1828]
**Describe the bug**
I am deploying this application in cloud foundry platform and was able to launch the UI app. We are having kafka instances as backing services and I used the env variable **KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS** to point it to the IP address as shown in our backing services.

But the service fails with the following stack 
![Screen Shot 2022-04-12 at 4 39 05 PM](https://user-images.githubusercontent.com/3452073/163049690-9463ad72-299d-421f-b7a0-ac512b03c74c.png)

Should I set any other environment variable to get this working. This tool would really benefit my team if I am able to enable it. Please guide us.

**Comment by Thilaknath** [comment]
Hello Team, 

I am also seeing an out of memory issue, Further attaching in the logs. I have set 3G for memory for this app. But still it complain
![Screen Shot 2022-04-12 at 4 43 42 PM](https://user-images.githubusercontent.com/3452073/163050540-ba51bb46-0984-4c94-af49-005b604d2f45.png)
s

**Comment by Haarolean** [comment]
Hi, please provide the required information requested in the issue template. And attach full container logs in text format.

**Comment by Thilaknath** [comment]
**Set up**
1) We are running the app in cloud foundry(similar to heroku), I am deploying the latest jar as offered here 
https://github.com/provectus/kafka-ui/releases/tag/0.3.3

**Steps to Reproduce**
1) Deploy the app in cloud foundry with kafka service binding (This is offered from our cloud platform)

**Expected behavior**
1) After binding the service kafka-ui should be able to connect to our kafka cluster. 
2) Our applications connect to kafka cluster using the certificate and client_ssl parameter.

[kafka-ui-logs.txt](https://github.com/provectus/kafka-ui/files/8481486/kafka-ui-logs.txt)

Please reach out to me if you need any more info

**Comment by Haarolean** [comment]
There seem to be at least a few issues. Let's start with the memory one.
So, you're running the app via jar file? Do you have control over jvm args? If yes, what args do you run the app with?

**Comment by Thilaknath** [comment]
Hello @Haarolean , So i resolved the memory issue and the app starts fine now. I am currently getting this error 

`2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 2022-04-13 14:59:14,820 WARN  [kafka-admin-client-thread | adminclient-1] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:430)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:514)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:368)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:291)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1333)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1264)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/java.lang.Thread.run(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.validator.Validator.validate(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.security.FileWatchingX509ExtendedTrustManager.checkServerTrusted(FileWatchingX509ExtendedTrustManager.java:73)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.security.DelegatingX509ExtendedTrustManager$6.accept(DelegatingX509ExtendedTrustManager.java:102)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.security.DelegatingX509ExtendedTrustManager.with(DelegatingX509ExtendedTrustManager.java:143)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.security.DelegatingX509ExtendedTrustManager.checkServerTrusted(DelegatingX509ExtendedTrustManager.java:98)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	... 20 common frames omitted
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
   2022-04-13T10:59:14.82-0400 [APP/PROC/WEB/0] OUT 	... 29 common frames omitted
`

**Comment by Thilaknath** [comment]
I am doing a cf push to cloud foundry something like this 

`cf push dom-kafka-ui -p kafka-ui-0.3.3.jar` after doing this, I set the above environment variables, Add binding to the available kafka service in our cf space and restart my application.

**Comment by Haarolean** [comment]
I see that you're not specifying paths to the keystore location (required for SSl).
Try [this](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ssl.yml#L18).

**Comment by Thilaknath** [comment]
Thanks, Current failure after adding the above config. The memory issue seems to be back. We can pass the JVM args as environment variables. What do you want me to set them as ?

The only config I pass ryt now related to Java is 
JBP_CONFIG_OPEN_JDK_JRE '{ jre: { version: 13.+ }, memory_calculator: { stack_threads: 25 } }'

The above is to force cloud foundry to use latest build pack to run Kafka-ui app. Please refer logs after your changes above 
[full_logs.txt](https://github.com/provectus/kafka-ui/files/8483108/full_logs.txt)

**Comment by Haarolean** [comment]
Any ideas how much heap memory is allocated by default on your platform?
Try setting `-Xmx2g`, let's see how it goes, we can decrease the amount later (not sure how to pass it in your platform's config, again).

**Comment by Thilaknath** [comment]
Hello This is what I see in the run config while the app loads up

JVM Memory Configuration: -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=182676K

**Comment by Thilaknath** [comment]
I was able to overcome the memory issue by setting the following config 

`JAVA_OPTS | -XX:MaxDirectMemorySize=512M`

Please refer attached logs. These warnings from the logs are confusing
2022-04-13T13:12:24.06-0400 [APP/PROC/WEB/0] OUT 2022-04-13 17:12:24,064 INFO  [parallel-1] o.a.k.c.s.a.AbstractLogin: Successfully logged in.
   2022-04-13T13:12:24.09-0400 [APP/PROC/WEB/0] OUT 2022-04-13 17:12:24,094 WARN  [parallel-1] o.a.k.c.a.AdminClientConfig: The configuration 'protocol' was supplied but isn't a known config.
   2022-04-13T13:12:24.09-0400 [APP/PROC/WEB/0] OUT 2022-04-13 17:12:24,094 WARN  [parallel-1] o.a.k.c.a.AdminClientConfig: The configuration 'ssl.truststore.location' was supplied but isn't a known config.
   2022-04-13T13:12:24.09-0400 [APP/PROC/WEB/0] OUT 2022-04-13 17:12:24,094 WARN  [parallel-1] o.a.k.c.a.AdminClientConfig: The configuration 

[full_logs.txt](https://github.com/provectus/kafka-ui/files/8483388/full_logs.txt)

**Comment by Haarolean** [comment]
@Thilaknath please share your actual config now :)

**Comment by Thilaknath** [comment]
JAVA_OPTS | -XX:MaxDirectMemorySize=512M
KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: (I am pointing to IP's with 9093 port)
KAFKA_CLUSTERS_0_NAME: kae068e61dfd94181bf4b4dfeaeb21edb
KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL: SASL
KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="<our user name>" password="<our password>";
KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM_CONFIG: ""
KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /kafka.truststore.jks

**Comment by Thilaknath** [comment]
I am available in discord and am part of the group kafka-ui. Kindly let me know if you want me to join there as well. Thank you

**Comment by Haarolean** [comment]
no issues on kafka-ui side, just ssl configuration problems (CN verification)
