### ISSUE TITLE
Can't connect to azure event hub kafka interface 

### ISSUE THREAD

**Issue by WizzardMaker** [provectus/kafka-ui#2441]
**Describe the bug**

We wanted to monitor our azure event hub, which we mainly use as a kafka server.
The kafka interface works and our backend services can communicate with the kafka interface

Monitoring also works with kafka-tool/offset-explorer

But kafka-ui fails to connect to the hub with this error message:
```
2022-08-12 14:27:25,701 ERROR [parallel-6] c.p.k.u.s.MetricsService: Failed to collect cluster prod-event-hub info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster prod-event-hub
        at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
        at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
        at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
```

The kafka UI has full admin rights on the assigned user

**Set up**

Kafka-UI is setup with a standard docker compose:
```yaml
version: '2.7'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8085:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=prod-event-hub
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=***.servicebus.windows.net:9093
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username='$$ConnectionString' password='***;
```

**Expected behavior**

A functioning connection with the azure event hub

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look

**Comment by srferron** [comment]
Hi,

Im interested on the connection to Azure Events Hub too. 

Thanks!!

**Comment by Haarolean** [comment]
Seems like they [don't care ](https://github.com/Azure/azure-event-hubs-for-kafka/issues/61) that much about implementing describeConfigs.

TODO: look for a workaround

**Comment by srferron** [comment]
Thanks for the feedback @Haarolean !

**Comment by hueiyuan** [comment]
@Haarolean I would like to ask current kafka ui version whether have supported to connect Azure Eventhub?

**Comment by Haarolean** [comment]
@hueiyuan thanks for the reminder

Might be doable now considering #3376,

@iliax PTAL

**Comment by hueiyuan** [comment]
@Haarolean Thanks for your reply. so maybe can I connect eventhub in `release 0.5.0`?
By the way, also please @iliax to confirm it. thank you.

**Comment by Haarolean** [comment]
@hueiyuan no you can't since this issue is still open.

**Comment by robsonpeixoto** [comment]
The same problem here with MSK(AWS) Kafka 1.1.1.

**Comment by Haarolean** [comment]
@robsonpeixoto MSK (even serverless) is fully supported. Try `master`-labeled docker image and if it doesn't work, raise a new issue/discussion.

**Comment by FireDrunk** [comment]
I'm having the same issues, and using the `master` tagged Docker image doesn't help.
The same `UnknownTopicOrPartitionException: This server does not host this topic-partition` error keeps popping up unfortunately.

**Comment by iliax** [comment]
@WizzardMaker @FireDrunk @hueiyuan hey guys, can you please verify it works for you on `master` - tagged docker image?

**Comment by WizzardMaker** [comment]
Can confirm that it works with the newest master branch image

**Comment by hueiyuan** [comment]
@iliax @WizzardMaker 
After verifying, my kafka ui does not connect eventhub. Could you give connect example of docker-compose.yaml ? My error message is below:
```
kafka-ui  | 2023-03-27 01:02:12,188 WARN  [kafka-admin-client-thread | kafka-ui-admin-1679878922-2] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1679878922-2] Connection to node -1 (<my-eventhub-namespace>.servicebus.windows.net/40.78.253.136:9093) could not be established. Broker may not be available.
```

I also provide my docker-compose.yaml for your reference:
```yaml
version: '3'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=prod-event-hub
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=<my-eventhub-namespaces>.servicebus.windows.net:9093
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username='$ConnectionString' password='Endpoint=sb://<my-eventhub-namespaces>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<my-key>';
```

**Comment by WizzardMaker** [comment]
> @iliax @WizzardMaker After verifying, my kafka ui still does not connect eventhub. Could you give connect example of docker-compose.yaml ? My error message is below:
> 
> ```
> kafka-ui  | 2023-03-27 01:02:12,188 WARN  [kafka-admin-client-thread | kafka-ui-admin-1679878922-2] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1679878922-2] Connection to node -1 (<my-eventhub-namespace>.servicebus.windows.net/40.78.253.136:9093) could not be established. Broker may not be available.
> ```
> 
> I also provide my docker-compose.yaml for your reference:
> 
> ```yaml
> version: '3'
> 
> services:
>   kafka-ui:
>     image: provectuslabs/kafka-ui:master
>     container_name: kafka-ui
>     ports:
>       - "8080:8080"
>     restart: always
>     environment:
>       - KAFKA_CLUSTERS_0_NAME=prod-event-hub
>       - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
>       - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=<my-eventhub-namespaces>.servicebus.windows.net:9093
>       - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
>       - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username='$ConnectionString' password='Endpoint=sb://<my-eventhub-namespaces>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<my-key>';
> ```

That error message looks more like a general connection problem, and not the problem discussed in this issue.

Are you sure, that your at all able to connect to your event hub at that address? (What is \<my-eventhub-namespaces\>? Make sure that this is the name of the Azure resource - Check your "Host name" Property of the Event Hub Resource)

**Comment by hueiyuan** [comment]
@WizzardMaker 
`<my-eventhub-namespaces>` just is a namespace of eventhub. You can image this is a variable which can be replaced. Because I do not want to paste complete host name here. Based on this reason, I have confirm my host name of eventhub is correct. So I not sure and want to confirm this configure of docker-compose.yaml whether have incorrect setting.

**Comment by WizzardMaker** [comment]
The configuration looks correct.

Is the network of your docker container restricted in any way? Can you open a shell on the container and ping to the internet (`ping google.com` for example)?

**Comment by hueiyuan** [comment]
@WizzardMaker 
`ping google.com` this command is work. but container still does not show `[AdminClient clientId=kafka-ui-admin-1679904082-4] Connection to node -1 (xxxxxx.servicebus.windows.net/20.83.192.11:9093) could not be established. Broker may not be available`

**Comment by hueiyuan** [comment]
@WizzardMaker 
`ping google.com` this command is work. But currently status is changed as timeout related issues:
```
INFO  [kafka-admin-client-thread | kafka-ui-admin-1679907761-1] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1679907761-1] Disconnecting from node -1 due to socket connection setup timeout
```

Do you have a idea about processing this problem?

**Comment by hueiyuan** [comment]
@WizzardMaker @iliax 
I have below error message, could you give some idea to solve it for me? Thank you.
```
[AdminClient clientId=kafka-ui-admin-1680100319-1] Connection to node -1 (xxxx.servicebus.windows.net/20.83.192.11:9093) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
```

**Comment by mvitor** [comment]
Worked like a charm for me. Great job, Thanks!
