### ISSUE TITLE
Getting error after launching the kafka-ui

### ISSUE THREAD

**Issue by sunny092318** [provectus/kafka-ui#2767]
I'm trying to setup the kafka-ui for my project. After launching the kafka-ui getting below error. I need to authenticate kafka cluster through kafka SASl.
500 Internal Server Error
Error while creating AdminClient for Cluster test-kafka

java.lang.IllegalStateException: Error while creating AdminClient for Cluster test-kafka
        at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
        at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.Operators.error(Operators.java:198)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:135)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4385)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
        at reactor.core.publisher.Operators.complete(Operators.java:137)
        at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: null
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at java.base/java.util.Properties.put(Properties.java:1301)
        at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$2(AdminClientServiceImpl.java:39)
        at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:86)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)
        ... 16 common frames omitted
2022-10-17 17:23:43,662 DEBUG [parallel-1] c.p.k.u.s.ClustersMetricsScheduler: Metrics updated for cluster: test-kafka
2022-10-17 17:24:13,660 DEBUG [parallel-1] c.p.k.u.s.ClustersMetricsScheduler: Start getting metrics for kafkaCluster: test-kafka
2022-10-17 17:24:13,662 ERROR [parallel-1] c.p.k.u.s.MetricsService: Failed to collect cluster test-kafka info

**Comment by Haarolean** [comment]
Hi, please follow the bug issue template and share the required details (app version, config, etc.)

**Comment by sunny092318** [comment]
Describe issue:

Once after the deploying the kafka ui jar through application yaml file on premises host, getting the below error. Basically we are trying to setup SASL connection with kafka-ui to our kafka cluster.
=====
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'http_proxy' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'no_proxy' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'ssl_keystore_location' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'https_proxy' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'ssl_truststore_location' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'ssl_truststore_password' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'keytab' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'sasl_jaas_config' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'ssl_key_password' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'principal' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'ssl_keystore_password' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'opts' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'sasl_mechanism' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'security_protocol' was supplied but isn't a known config.
2022-10-18 14:28:00,614 WARN  [parallel-2] o.a.k.c.a.AdminClientConfig: The configuration 'sasl_kerberos_service_name' was supplied but isn't a known config.
2022-10-18 14:28:00,614 INFO  [parallel-2] o.a.k.c.u.AppInfoParser: Kafka version: 2.8.0
2022-10-18 14:28:00,614 INFO  [parallel-2] o.a.k.c.u.AppInfoParser: Kafka commitId: ebb1d6e21cc92130
2022-10-18 14:28:00,614 INFO  [parallel-2] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1666099680614
2022-10-18 14:28:14,828 INFO  [kafka-admin-client-thread | adminclient-2] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-2] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1666099694756, tries=1, nextAllowedTryMs=1666099694928) timed out at 1666099694828 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-10-18 14:28:15,397 ERROR [parallel-2] c.p.k.u.s.MetricsService: Failed to collect cluster staging-kafka info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster staging-kafka
        at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
        at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
        at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1666099695394, tries=1, nextAllowedTryMs=1666099695496) timed out at 1666099695396 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
2022-10-18 14:28:15,397 DEBUG [parallel-2] c.p.k.u.s.ClustersMetricsScheduler: Metrics updated for cluster: staging-kafka
2022-10-18 14:28:15,401 DEBUG [parallel-1] c.p.k.u.s.ClustersMetricsScheduler: Start getting metrics for kafkaCluster: staging-kafka
2022-10-18 14:28:15,402 INFO  [parallel-1] o.a.k.c.a.AdminClientConfig: AdminClientConfig values:
        bootstrap.servers = [10.127.29.180:9092, 10.127.29.181:9092, 10.127.29.182:9092, 10.127.29.183:9092]
        client.dns.lookup = use_all_dns_ips
        client.id =
        connections.max.idle.ms = 300000
        default.api.timeout.ms = 60000
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        receive.buffer.bytes = 65536
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 2147483647
        retry.backoff.ms = 100
        sasl.client.callback.handler.class = null
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.login.callback.handler.class = null
        sasl.login.class = null
        sasl.login.refresh.buffer.seconds = 300
        sasl.login.refresh.min.period.seconds = 60
        sasl.login.refresh.window.factor = 0.8
        sasl.login.refresh.window.jitter = 0.05
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        security.providers = null
        send.buffer.bytes = 131072
        socket.connection.setup.timeout.max.ms = 30000
        socket.connection.setup.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
        ssl.endpoint.identification.algorithm = https
        ssl.engine.factory.class = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.certificate.chain = null
        ssl.keystore.key = null
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLSv1.3
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.certificates = null
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
=====

Expected Behaviors:

It should work normally after the connection

Configuration:

kafka:
  clusters:
    - name: kafka
      bootstrapServers: 10.x.x.x:9092,10.x.x.x:9092,10.x.x.x:9092,10.x.x.x:9092
      properties:
        opts: "-Djava.security.auth.login.config=/home/kafka_client_jaas.conf -Djava.security.krb5.conf=/etc/krb5.conf -Dsun.security.krb5.debug=true"
        principal: svc@GLOBAL.XYZ.ORG
        security_protocol: SASL_SSL
        keytab: /home/svc-kafka.keytab
        sasl_mechanism: GSSAPI
        sasl_kerberos_service_name: kafka
        ssl_truststore_location: /home/kafka_broker.truststore.pks.jks
        ssl_truststore_password: $$$$
        ssl_keystore_location: /home/kafka_broker.keystore.pks.jks
        ssl_keystore_password: $$$$
        ssl_key_password: $$$$
        sasl_jaas_config: 'com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true renewTicket=true useKeyTab=true keyTab="/home/svc-kafka.keytab" principal="svc-kafka@GLOBAL.xyz.org";'
      schemaRegistry: http://localhost:8085
      ksqldbServer: http://localhost:8088
      kafkaConnect:
        - name: first
          address: http://localhost:8083
      metrics:
        port: 9997
        type: JMX
spring:
  jmx:
    enabled: true
auth:
  type: disabled
server:
  kafka-ui
port:
  8080 #- Port in which kafka-ui will run.

kafka-ui App version:  kafka-ui-api-v0.4.0

**Comment by Haarolean** [comment]
@sunny092318 thanks, please take a look at this: #2118

**Comment by sunny092318** [comment]
@Haarolean Thanks for all your support, able to setup the kafka-ui for my project with SASL enabled mechanism.
Now trying to set authentication for kafka-ui dashboard, but its not working somehow. Below are my application.yml configuration. Any leads will be quiet helpful do we have define differently.

properties:
    metrics_username: abc
    metrics_password: abc

**Comment by Haarolean** [comment]
> @Haarolean Thanks for all your support, able to setup the kafka-ui for my project with SASL enabled mechanism. Now trying to set authentication for kafka-ui dashboard, but its not working somehow. Below are my application.yml configuration. Any leads will be quiet helpful do we have define differently.
> 
> properties: metrics.username: abc metrics.password: abc

eh, do you want to set up auth for the ui itself? 
Check [this](https://github.com/provectus/kafka-ui/wiki/FAQ#basic-username-password-authentication):

**Comment by sunny092318** [comment]
@Haarolean Thanks for the details. Does kafka-ui support on LDAP mechanism, because I have defined below parameter in application.yaml file but it doesn't change anything. From the log can see **configuring LDAP authentication** so means LDAP configuration done or in progress.

====
spring.ldap.url=ldap://localhost:18889
spring.ldap.base=dc=example,dc=com
spring.ldap.username=uid=admin,ou=system
spring.ldap.password=secret
====

**Comment by Haarolean** [comment]
> This issue has been automatically marked as stale because no requested feedback has been provided. It will be closed if no further activity occurs. Thank you for your contributions.

bad bot

**Comment by Haarolean** [comment]
> @Haarolean Thanks for the details. Does kafka-ui support on LDAP mechanism, because I have defined below parameter in application.yaml file but it doesn't change anything. From the log can see **configuring LDAP authentication** so means LDAP configuration done or in progress.
> 
> spring.ldap.url=ldap://localhost:18889 spring.ldap.base=dc=example,dc=com spring.ldap.username=uid=admin,ou=system spring.ldap.password=secret

Yes it does. The link is available in the same wiki, click [here](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/auth-ldap.yaml#L29). Please use the env variables provided there.

**Comment by sunny092318** [comment]
I have tried providing the below parameter in application.yaml since installing on through servers not with containers approach.
Is there something doing wrong or any change require on ldap server also. Please suggest

spring:
  jmx:
    enabled: true

auth.type: "ldap"
spring.ldap.urls: "ldap://example:389"
spring.ldap.userfilter.searchbase: "dc=g,dc=first,dc=org"
spring.ldap.userfilter.searchfilter: "cn=one,ou=Service accounts,ou=Management,ou=india,dc=g,dc=first,dc=org"
spring.ldap.adminuser: "cn=one,ou=Service accounts,ou=Management,ou=india,dc=global,dc=first,dc=org"
spring.ldap.adminpassword: "xxxx"

**Comment by Haarolean** [comment]
> This issue has been automatically marked as stale because no requested feedback has been provided. It will be closed if no further activity occurs. Thank you for your contributions.

bad bot

**Comment by Haarolean** [comment]
@sunny092318 if you're running the jar, your config should be a valid yaml file :)

```
spring:
  jmx: 
    enabled: true
  ldap:
    urls: "ldap://example:389"
#...


auth:
  type: "ldap"
```

**Comment by sunny092318** [comment]
@Haarolean Thanks for providing the details. I think its not related to yaml syntax since if it was yaml error then it couldn't allow me to run kafka-ui app. 
I think its something related to ldap configuration because even passing all parameter it doesn't allow me  to login.

**Comment by Haarolean** [comment]
@sunny092318 well, the [example](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/auth-ldap.yaml#L29) does work fine, all the credentials from `rroemhild/test-openldap` are getting accepted.
Can you provide a setup with docker-compose to reproduce to issue you're having?
On the side note, a suggestion to turn on finer logging via this env. property:
`logger.level.org.springframework.security=DEBUG`
