### ISSUE TITLE
Message tab infinite polling

### ISSUE THREAD

**Issue by nitin1677** [provectus/kafka-ui#2935]
**Describe the bug**

After latest pull from master today, kafka-ui broke and no events are being displayed in ui. Switch to Kafka Cluster > topics > navigate to topic. Topic overview tab shows correct information. 

When navigate to messages tab, none of the events displayed in data grid and result is:
Polling 0 ms 0 Bytes 0 messages consumed

From docker logs, error is:
2022-11-15 00:06:24,483 ERROR [boundedElastic-4] r.c.s.Schedulers: Scheduler worker in group main failed with an uncaught exception
java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.pure.UnsafeUtil

The complete error stack is below.

**Set up**

docker pull provectuslabs/kafka-ui:master

11.14.2022 11:03:06
(
[8181499](https://github.com/provectus/kafka-ui/commit/8181499)
)

**Steps to Reproduce**

1.  docker pull provectuslabs/kafka-ui:master

**Expected behavior**

Events from kafka topics to be displayed in data grid.

**Screenshots**

**Additional context**

2022-11-15 00:06:24,224 INFO  [boundedElastic-4] o.a.k.c.Metadata: [Consumer clientId=kafka-ui-25f7d8b6-b232-4643-b483-40b0df3f28e7, groupId=null] Cluster ID: Zp6dCNprQFWXYfHx6rwlkw
2022-11-15 00:06:24,274 INFO  [boundedElastic-4] o.a.k.c.c.KafkaConsumer: [Consumer clientId=kafka-ui-25f7d8b6-b232-4643-b483-40b0df3f28e7, groupId=null] Subscribed to partition(s): TEST-TOPIC_V3-1, TEST-TOPIC_V3-2, TEST-TOPIC_V3-0
2022-11-15 00:06:24,275 INFO  [boundedElastic-4] o.a.k.c.c.KafkaConsumer: [Consumer clientId=kafka-ui-25f7d8b6-b232-4643-b483-40b0df3f28e7, groupId=null] Seeking to offset 131339 for partition TEST-TOPIC_V3-1
2022-11-15 00:06:24,275 INFO  [boundedElastic-4] o.a.k.c.c.KafkaConsumer: [Consumer clientId=kafka-ui-25f7d8b6-b232-4643-b483-40b0df3f28e7, groupId=null] Seeking to offset 134131 for partition TEST-TOPIC_V3-2
2022-11-15 00:06:24,275 INFO  [boundedElastic-4] o.a.k.c.c.KafkaConsumer: [Consumer clientId=kafka-ui-25f7d8b6-b232-4643-b483-40b0df3f28e7, groupId=null] Seeking to offset 132305 for partition TEST-TOPIC_V3-0
2022-11-15 00:06:24,480 INFO  [boundedElastic-4] o.a.k.c.m.Metrics: Metrics scheduler closed
2022-11-15 00:06:24,480 INFO  [boundedElastic-4] o.a.k.c.m.Metrics: Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-11-15 00:06:24,480 INFO  [boundedElastic-4] o.a.k.c.m.Metrics: Metrics reporters closed
2022-11-15 00:06:24,482 INFO  [boundedElastic-4] o.a.k.c.u.AppInfoParser: App info kafka.consumer for kafka-ui-25f7d8b6-b232-4643-b483-40b0df3f28e7 unregistered
2022-11-15 00:06:24,483 WARN  [boundedElastic-4] r.c.Exceptions: throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.pure.UnsafeUtil
        at org.xerial.snappy.pure.SnappyRawDecompressor.getUnsignedByteSafe(SnappyRawDecompressor.java:323)
        at org.xerial.snappy.pure.SnappyRawDecompressor.readUncompressedLength(SnappyRawDecompressor.java:288)
        at org.xerial.snappy.pure.SnappyRawDecompressor.getUncompressedLength(SnappyRawDecompressor.java:42)
        at org.xerial.snappy.pure.PureJavaSnappy.uncompressedLength(PureJavaSnappy.java:238)
        at org.xerial.snappy.Snappy.uncompressedLength(Snappy.java:638)
        at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:435)
        at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:466)
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
        at org.apache.kafka.common.utils.ByteUtils.readUnsignedVarint(ByteUtils.java:170)
        at org.apache.kafka.common.utils.ByteUtils.readVarint(ByteUtils.java:205)
        at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:281)
        at org.apache.kafka.common.record.DefaultRecordBatch$2.doReadRecord(DefaultRecordBatch.java:296)
        at org.apache.kafka.common.record.DefaultRecordBatch$StreamRecordIterator.readNext(DefaultRecordBatch.java:638)
        at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:603)
        at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:572)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.nextFetchedRecord(Fetcher.java:1618)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1653)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1494)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:716)
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:682)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1313)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1242)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1215)
        at com.provectus.kafka.ui.emitter.AbstractEmitter.poll(AbstractEmitter.java:40)
        at com.provectus.kafka.ui.emitter.AbstractEmitter.poll(AbstractEmitter.java:34)
        at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:45)
        at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:14)
        at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:95)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-15 00:06:24,483 WARN  [boundedElastic-4] r.c.Exceptions: throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.pure.UnsafeUtil
        at org.xerial.snappy.pure.SnappyRawDecompressor.getUnsignedByteSafe(SnappyRawDecompressor.java:323)
        at org.xerial.snappy.pure.SnappyRawDecompressor.readUncompressedLength(SnappyRawDecompressor.java:288)
        at org.xerial.snappy.pure.SnappyRawDecompressor.getUncompressedLength(SnappyRawDecompressor.java:42)
        at org.xerial.snappy.pure.PureJavaSnappy.uncompressedLength(PureJavaSnappy.java:238)
        at org.xerial.snappy.Snappy.uncompressedLength(Snappy.java:638)
        at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:435)
        at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:466)
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
        at org.apache.kafka.common.utils.ByteUtils.readUnsignedVarint(ByteUtils.java:170)
        at org.apache.kafka.common.utils.ByteUtils.readVarint(ByteUtils.java:205)
        at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:281)
        at org.apache.kafka.common.record.DefaultRecordBatch$2.doReadRecord(DefaultRecordBatch.java:296)
        at org.apache.kafka.common.record.DefaultRecordBatch$StreamRecordIterator.readNext(DefaultRecordBatch.java:638)
        at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:603)
        at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:572)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.nextFetchedRecord(Fetcher.java:1618)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1653)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1494)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:716)
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:682)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1313)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1242)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1215)
        at com.provectus.kafka.ui.emitter.AbstractEmitter.poll(AbstractEmitter.java:40)
        at com.provectus.kafka.ui.emitter.AbstractEmitter.poll(AbstractEmitter.java:34)
        at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:45)
        at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:14)
        at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:95)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-15 00:06:24,483 ERROR [boundedElastic-4] r.c.s.Schedulers: Scheduler worker in group main failed with an uncaught exception
java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.pure.UnsafeUtil
        at org.xerial.snappy.pure.SnappyRawDecompressor.getUnsignedByteSafe(SnappyRawDecompressor.java:323)
        at org.xerial.snappy.pure.SnappyRawDecompressor.readUncompressedLength(SnappyRawDecompressor.java:288)
        at org.xerial.snappy.pure.SnappyRawDecompressor.getUncompressedLength(SnappyRawDecompressor.java:42)
        at org.xerial.snappy.pure.PureJavaSnappy.uncompressedLength(PureJavaSnappy.java:238)
        at org.xerial.snappy.Snappy.uncompressedLength(Snappy.java:638)
        at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:435)
        at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:466)
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
        at org.apache.kafka.common.utils.ByteUtils.readUnsignedVarint(ByteUtils.java:170)
        at org.apache.kafka.common.utils.ByteUtils.readVarint(ByteUtils.java:205)
        at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:281)
        at org.apache.kafka.common.record.DefaultRecordBatch$2.doReadRecord(DefaultRecordBatch.java:296)
        at org.apache.kafka.common.record.DefaultRecordBatch$StreamRecordIterator.readNext(DefaultRecordBatch.java:638)
        at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:603)
        at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:572)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.nextFetchedRecord(Fetcher.java:1618)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1653)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1494)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:716)
        at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:682)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1313)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1242)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1215)
        at com.provectus.kafka.ui.emitter.AbstractEmitter.poll(AbstractEmitter.java:40)
        at com.provectus.kafka.ui.emitter.AbstractEmitter.poll(AbstractEmitter.java:34)
        at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:45)
        at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:14)
        at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:95)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-11-15 00:06:25,123 DEBUG [parallel-3] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: KAFKA_QA

**Comment by iliax** [comment]
@nitin1677 
updated docker image published (master tag) 
can you please check on your setup?

**Comment by nitin1677** [comment]
Updated the docker image with pull from master. No more error in docker logs. 

1. Topics without schema (Key serde: String, Value serde: String, Partitions: All items are selected) are able to pull the events and display in data grid.

2. Topics with schema (Key serde: SchemaRegistry, Value serde: SchemaRegistry, Partitions: All items are selected) are not able to pull the events and result in data grid is, No messages found (2997 ms, 0 Bytes, 0 messages consumed)
    2.1 From partitions list, select a partition (Partition#0) and data grid will display the events from select partition, 123 ms, 663 
    KB, 500 messages consumed.

**Comment by iliax** [comment]
@nitin1677 thank you for checking
looks like snappy issue is solved, as for 2. that you mention - looks like it is separate issue, lets create ticket for that.

To finally verify that snappy works fine - can you please run topic analysis (Statistics tab) on both SR and non-SR topic?

**Comment by iliax** [comment]
@nitin1677 thank you for confirmation!
