### ISSUE TITLE
Connection to SSL bootstrapServer from local Kafka-ui throwing SslAuthenticationException

### ISSUE THREAD

**Issue by aav789** [provectus/kafka-ui#2956]
Request you to please help with corrections to application-local.yml
_I am able to connect to the SSL cluster via Offset Explorer 2.0 using the exact same trustStore and keyStore._

 
**Describe the bug**

Connection to SSL bootstrapServer from local Kafka-ui throwing SslAuthenticationException

`Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)
	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:430)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:514)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:368)
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:291)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1333)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
	... 19 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 24 common frames omitted`

**Set up**
Downloaded `kafka-ui-api-v0.4.0.jar` and created `application-local.yml` with below configuration: 

kafka:
  clusters:
    - name: local
      bootstrapServers: 10.0.0.5:9092
      zookeeper: 10.0.0.5:2181
      metrics:
        port: 9997
        type: JMX
    -
      name: stage 
      bootstrapServers: kafka-abcd:9093
      metrics:
        port: 9998
        type: JMX
      properties:
        security.protocol: SSL  
      schemaRegistrySsl:
        keystoreLocation: path_of_file/keystore.jks
        keystorePassword: password
        truststoreLocation: path_of_file/truststore.jks
        truststorePassword: password
spring:
  jmx:
    enabled: true
auth:
  type: DISABLED
server:
  port: 8099

**Steps to Reproduce**

1. I run the kafka-util using the below command 
` java -Dspring.config.additional-location=location_of_file/application-local.yml -jar location_of_file/kafka-ui-api-v0.4.0.jar` 

At the start of the logs, I see below parameters for the SSL (stage) cluster. For some reason it is not picking up the SSL configurations passed via yml file.

	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = SSL
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS

 
**Expected behavior**
Kafka-util starts up but starts throwing errors as mentioned above. I can conect to my local cluster but not to the cluster via SSL.

**Comment by aav789** [comment]
Request you to please help me with the correct yml file.

**Comment by Haarolean** [comment]
@aav789 hi, thanks for reaching out.
Can you please format the `application-local.yml` contents with backticks? Without the indentation the config is unreadable.

**Comment by aav789** [comment]
`kafka:
  clusters:
    - name: local
      bootstrapServers: 10.0.0.5:9092
      zookeeper: 10.0.0.5:2181
      metrics:
        port: 9997
        type: JMX
    -
      name: stage 
      bootstrapServers: kafka-abcd:9093
      metrics:
        port: 9998
        type: JMX
      schemaRegistrySsl:
        keystoreLocation: path_of_file/keystore.jks
        keystorePassword: password
        truststoreLocation: path_of_file/truststore.jks
        truststorePassword: password
      properties:
        security.protocol: SSL
spring:
  jmx:
    enabled: true
auth:
  type: DISABLED
server:
  port: 8099 `

**Comment by aav789** [comment]
Hi @Haarolean,
Request you to please provide solution when you get a chance.
Thank you.

**Comment by Haarolean** [comment]
@aav789 the problem is that you provide the truststore/keystore just for the schemaregistry, but not for the kafka itself. 
Check [this](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ssl.yml)
Let me know if you have any further problems

**Comment by Haarolean** [comment]
@aav789 there's no such thing like "docker properties". Any configs you see are convertable back and forth. Uppercase-like properties are just a representation of yaml properties, where an underscore is an indentation in yaml.
`KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION` would be like this:
```
kafka:
  clusters:
    - name: "test"
      properties:
        ssl_keystore_location: "/path/name"
```

**Comment by aav789** [comment]
@Haarolean  - I am able to see the ssl properties in the yaml file as parameters when I run kafka-ui.

Would you like me to open a new issue for the below error I see. Not sure this is anything to do with kafka-ui and more to do with my internal cluster connection using the properties. If you have some idea would be glad if you help.

Thank you.
 
`2022-12-05 22:36:16,157 ERROR [parallel-1] c.p.k.u.s.MetricsService: Failed to collect cluster stage scus info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster stage scus
	at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.`

**Comment by aav789** [comment]
@Haarolean @th0ger - I dont think the issue `https://github.com/provectus/kafka-ui/issues/2856` is connected atleast for now. 

last sentence says - Cluster authorization failed
Am i giving some property incorrectly since the same keystore/truststore/password is working in Offset Explorer

**Comment by Haarolean** [comment]
@aav789 we have an answer to this issue in our [FAQ](https://github.com/provectus/kafka-ui/wiki/Common-problems#cluster-authorization-failed)
Basically, this means the user you use to authenticate to your kafka doesn't have the required permissions for certain actions. We'd need describeconfigs, describelogdirs for cluster; describe, describeconfigs for topics; and other r/w permissions if you wish to use it in r/w mode.

**Comment by th0ger** [comment]
@aav789 I linked this issue by mistake, it was corrected.

**Comment by aav789** [comment]
@Haarolean - If there is a way to only perform the actions the user has permissions for then I am sure the issue seen by me will help many. There should be a work around for this.

**Comment by Haarolean** [comment]
@aav789 we have plans to refactor this stuff within #1452
