### ISSUE TITLE
Null Pointer Exception after saving changes during edit settings of the Topic

### ISSUE THREAD

**Issue by antipova0803** [provectus/kafka-ui#299]
**Pre-conditions:** 
Kafka has a Topic

**Steps:** 
1. Navigate to the Topic 
2. Click “Edit settings”
3. Click “Submit”

**Expected:** 
Successfully saving of the setting changes 

**Actual:** 
The app is freezing. Null point exception in the console. 

```
java.lang.NullPointerException: null
   at org.apache.commons.pool2.impl.GenericKeyedObjectPool.returnObject(GenericKeyedObjectPool.java:470) ~[commons-pool2-2.2.jar!/:2.2]
   at com.provectus.kafka.ui.util.JmxClusterUtil.getJmxMetrics(JmxClusterUtil.java:47) ~[classes!/:?]
   at com.provectus.kafka.ui.service.KafkaService.lambda$getJmxMetric$53(KafkaService.java:413) ~[classes!/:?]
   at java.util.Optional.map(Optional.java:258) ~[?:?]
   at com.provectus.kafka.ui.service.KafkaService.getJmxMetric(KafkaService.java:413) ~[classes!/:?]
   at com.provectus.kafka.ui.service.KafkaService.lambda$fillBrokerMetrics$55(KafkaService.java:424) ~[classes!/:?]
   ...
ERROR com.provectus.kafka.ui.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://kafka1:9998/jmxrmi
```

**Comment by germanosin** [comment]
@antipova0803, thank you for creating issue. We'll try to  find a root cause and fix it soon. Look's like we are triyng to connect jmx port after topic settings update without success.

**Comment by iliax** [comment]
Exception is not connected with Null Pointer Exception. There is not request to BE after Submit button click (you can see it if you open UI console).
@workshur can you please check what is going on UI ?
