### ISSUE TITLE
Error creating bean with name 'OAuthLogoutSuccessHandler'

### ISSUE THREAD

**Issue by dorsegal** [provectus/kafka-ui#3146]
```
auth:
  type: OAUTH2
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            clientId: id
            clientSecret: secret
            scope: scopes
         provider:
           azure:
             issuer-uri: uri
```

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'OAuthLogoutSuccessHandler' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/config/auth/logout/OAuthLogoutSuccessHandler.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultOidcLogoutHandler' defined in class path resource [com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.class]: Unsatisfied dependency expressed through method 'defaultOidcLogoutHandler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryReactiveClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalArgumentException: registrations cannot be null or empty
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.provectus.kafka.ui.KafkaUiApplication.main(KafkaUiApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultOidcLogoutHandler' defined in class path resource [com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.class]: Unsatisfied dependency expressed through method 'defaultOidcLogoutHandler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryReactiveClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalArgumentException: registrations cannot be null or empty
```

I used same config at v0.4.0, everything works as expected.

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

Sorry, it seems I forgot to mention this in a changelog, you have to reformat the config a little bit (even if you're not gonna use RBAC)

Before: authentication properties were placed on the level `spring.security.oauth2.client.[registration|provider].<provider>.<property>`
Now: `auth.oauth2.client.<provider>.<property>`
An example:
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/1494347/209645575-7472154f-609e-491d-a1a4-d9a956aca04f.png">
Please refer to this [article](https://github.com/provectus/kafka-ui/wiki/OAuth-Configuration) for examples for different oauth providers.

Let me know if that's clear enough. I've updated the changelog as well.

**Comment by ivanpedersen** [comment]
@Haarolean Does this also need to be updated then? https://github.com/provectus/kafka-ui/blob/master/documentation/guides/SSO.md
I'm using Azure and got this issue trying to run v0.5.0 today (was on "v0.4.0" before).

**Comment by Haarolean** [comment]
@ivanpedersen yep! we're also going to update all the docs soon

**Comment by ivanpedersen** [comment]
@stephaneuh 
I'm using Azure with these settings:
```
- name: AUTH_TYPE
  value: OAUTH2
- name: AUTH_OAUTH2_CLIENT_AUTH0_PROVIDER
  value: azure
- name: AUTH_OAUTH2_CLIENT_AUTH0_CLIENTNAME
  value: azure
- name: AUTH_OAUTH2_CLIENT_AUTH0_CUSTOMPARAMS_TYPE
  value: azure
- name: AUTH_OAUTH2_CLIENT_AUTH0_CLIENTSECRET
  valueFrom:
    secretKeyRef:
      name: my-k8s-secret
      key: clientsecret # Secret created in Azure portal
- name: AUTH_OAUTH2_CLIENT_AUTH0_SCOPE
  value: "https://graph.microsoft.com/User.Read"
- name: AUTH_OAUTH2_CLIENT_AUTH0_ISSUER_URI
  value: "https://login.microsoftonline.com/DIRECTORY_TENANT_ID/v2.0" # Replace with Directory (tenant) ID from the Azure portal
- name: AUTH_OAUTH2_CLIENT_AUTH0_CLIENTID
  value: APP_CLIENT_ID # Replace with Application (client) ID from the Azure portal
  ```
  See the comment, https://github.com/provectus/kafka-ui/issues/3146#issuecomment-1365757583
 You probably need to rename those variables given that you run the latest 0.5.0 release

**Comment by Haarolean** [comment]
@stephaneuh please refer to @ivanpedersen's reply 
@ivanpedersen thank you :)

**Comment by andreyolv** [comment]
@ivanpedersen Can you share the parameters you used in your yaml in yamlApplicationConfig.auth.oauth2.client.azure?
for me to have as an example, thank you

**Comment by ivanpedersen** [comment]
@andreyolv I'm not sure I understand what you mean by that? I've listed the Azure related parameters in the comment above, you're saying that I've missed some?

**Comment by andreyolv** [comment]
@ivanpedersen you listed the environment variables, right? 
I'm editing the .values file of the helm chart in the example below

```
env: 
    - name: KAFKA_CLUSTERS_0_NAME
      value: cdc
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: http://cdc-kafka-bootstrap.kafka-strimzi.svc.cluster.local:9092
    - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
      value: http://schema-registry-cp-schema-registry.kafka-strimzi.svc.cluster.local:8081
    - name: KAFKA_CLUSTERS_0_KSQLDBSERVER
      value: http://ksqldb-server.kafka-strimzi.svc.cluster.local:8088
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
      value: connect-cluster
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
      value: http://connect-cluster-connect-api.kafka-strimzi.svc.cluster.local:8083
    - name: AUTH_TYPE
      value: OAUTH2
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTID
      value: 
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTSECRET
      value: 
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_SCOPE
      value: "https://graph.microsoft.com/User.Read"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTH0_ISSUER_URI
      value: "https://login.microsoftonline.com/{tenant-id}/v2.0"    
yamlApplicationConfig:
  kafka:
    clusters:
    - name: gac-cdc
      bootstrapServers: cdc-kafka-bootstrap.kafka-strimzi.svc.cluster.local:9092
    auth:
      type: OAUTH2
        oauth2:
          client:
            azure:
              **(what parameters do I put here?)** @ivanpedersen 
      rbac:
        roles:
        - name: "admin"
            clusters:
              - gac-cdc
            subjects:
               ....
```
