### ISSUE TITLE
MSK support broken for 0.5.0

### ISSUE THREAD

**Issue by jsmaupin** [provectus/kafka-ui#3174]
MSK support was working for us in version 0.4.0, but now throws an exception in 0.5.0.  The dashboard shows the cluster is down and the associated pages all timeout and only show a blank, white page.  I can easily reproduce this by switching between versions 0.4.0 and 0.5.0.  This is reproducible on clusters without authentication and data is sent via PLAINTEXT.  The broker version is 2.2.1.

**Set up**
We deploy using docker-compose with a config that looks much like this:
```yaml
version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=Prod
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=mskbroker1:9092,mskbroker2:9092...
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper1:2181,zookeeper2:2181...
```
I've tried setting `KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT`, but this did not help.

The following exception is thrown in the logs:
```
kafka-ui  | 2022-12-28 22:42:45,463 ERROR [parallel-18] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [e3d29b7e-17]  500 Server Error for HTTP GET "/api/clusters/<redacted>/brokers"
kafka-ui  | java.lang.IllegalStateException: Error while creating AdminClient for Cluster <redacted>
kafka-ui  |     at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
kafka-ui  |     Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
kafka-ui  | Error has been observed at the following site(s):
kafka-ui  |     *__checkpoint ⇢ Handler com.provectus.kafka.ui.controller.BrokersController#getBrokers(String, ServerWebExchange) [DispatcherHandler]
kafka-ui  |     *__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
kafka-ui  |     *__checkpoint ⇢ HTTP GET "/api/clusters/<redacted>/brokers" [ExceptionHandlingWebHandler]
kafka-ui  | Original Stack Trace:
kafka-ui  |             at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
kafka-ui  |             at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3776)
kafka-ui  |             at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
kafka-ui  |             at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
kafka-ui  |             at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
kafka-ui  |             at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
kafka-ui  |             at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
kafka-ui  |             at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
kafka-ui  |             at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
kafka-ui  |             at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
kafka-ui  |             at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
kafka-ui  |             at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
kafka-ui  |             at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
kafka-ui  |             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka-ui  |             at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
kafka-ui  |             at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
kafka-ui  |             at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
kafka-ui  |             at java.base/java.lang.Thread.run(Thread.java:833)
kafka-ui  | Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default includeClusterAuthorizedOperations at version 7
```

**Comment by iliax** [comment]
Hello @jsmaupin, 
can you please check docker  image with `master` ?

**Comment by Haarolean** [comment]
@jsmaupin please try the aforementioned solution. Ping me in this issue if that doesn't help.

**Comment by jsmaupin** [comment]
Sorry for the delayed response.  This appears to be fixed at TOT.  I tested using the tag 0048a7eabdd078606768487af74c4403f8142b60

**Comment by Haarolean** [comment]
@jsmaupin glad to hear :)
