### ISSUE TITLE
Running in eclipse 

### ISSUE THREAD

**Issue by pronzato** [provectus/kafka-ui#319]
Hi All,

Is there anything special we need to do to be able to run your Kafka-UI in eclipse?

I was able to build it without issue but when I try to run the KafkaUiApplication class I get the following:

`10:17:44.330 [main] INFO org.springframework.core.KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.

 

  .   ____          _            __ _ _

/\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \

( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \

\\/  ___)| |_)| | | | | || (_| |  ) ) ) )

  '  |____| .__|_| |_|_| |_\__, | / / / /

=========|_|==============|___/=/_/_/_/

:: Spring Boot ::        (v2.2.4.RELEASE)

 

2021-03-28 10:17:45.060  INFO 14476 --- [           main] c.provectus.kafka.ui.KafkaUiApplication  : Starting KafkaUiApplication on K9C7BEF232F05 with PID 14476 (C:\Work\gmdp\standalone\kafka-ui-0.0.10\kafka-ui-api\target\classes started by nbkgur4 in C:\Work\gmdp\standalone\kafka-ui-0.0.10\kafka-ui-api)

2021-03-28 10:17:45.062  INFO 14476 --- [           main] c.provectus.kafka.ui.KafkaUiApplication  : No active profile set, falling back to default profiles: default

2021-03-28 10:17:45.267  WARN 14476 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath

2021-03-28 10:17:46.461  WARN 14476 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clustersMetricsScheduler' defined in file [C:\Work\gmdp\standalone\kafka-ui-0.0.10\kafka-ui-api\target\classes\com\provectus\kafka\ui\cluster\ClustersMetricsScheduler.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clustersStorage' defined in file [C:\Work\gmdp\standalone\kafka-ui-0.0.10\kafka-ui-api\target\classes\com\provectus\kafka\ui\cluster\model\ClustersStorage.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.provectus.kafka.ui.cluster.model.ClustersStorage]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for com.provectus.kafka.ui.cluster.mapper.ClusterMapper

2021-03-28 10:17:46.535  INFO 14476 --- [           main] ConditionEvaluationReportLoggingListener :

 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2021-03-28 10:17:46.543 ERROR 14476 --- [           main] o.s.boot.SpringApplication               : Application run failed

 

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clustersMetricsScheduler' defined in file [C:\Work\gmdp\standalone\kafka-ui-0.0.10\kafka-ui-api\target\classes\com\provectus\kafka\ui\cluster\ClustersMetricsScheduler.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clustersStorage' defined in file [C:\Work\gmdp\standalone\kafka-ui-0.0.10\kafka-ui-api\target\classes\com\provectus\kafka\ui\cluster\model\ClustersStorage.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.provectus.kafka.ui.cluster.model.ClustersStorage]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for com.provectus.kafka.ui.cluster.mapper.ClusterMapper

                at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]

                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]

                at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]

                at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]

                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]

                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]

                at com.provectus.kafka.ui.KafkaUiApplication.main(KafkaUiApplication.java:14) ~[classes/:na]

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clustersStorage' defined in file [C:\Work\gmdp\standalone\kafka-ui-0.0.10\kafka-ui-api\target\classes\com\provectus\kafka\ui\cluster\model\ClustersStorage.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.provectus.kafka.ui.cluster.model.ClustersStorage]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for com.provectus.kafka.ui.cluster.mapper.ClusterMapper

                at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                ... 19 common frames omitted

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.provectus.kafka.ui.cluster.model.ClustersStorage]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for com.provectus.kafka.ui.cluster.mapper.ClusterMapper

                at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:216) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                ... 33 common frames omitted

Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for com.provectus.kafka.ui.cluster.mapper.ClusterMapper

                at org.mapstruct.factory.Mappers.getMapper(Mappers.java:61) ~[mapstruct-1.3.1.Final.jar:na]

                at com.provectus.kafka.ui.cluster.model.ClustersStorage.<init>(ClustersStorage.java:23) ~[classes/:na]

                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]

                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]

                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]

                at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]

                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]

                at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:203) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]

                ... 35 common frames omitted

Caused by: java.lang.ClassNotFoundException: Cannot find implementation for com.provectus.kafka.ui.cluster.mapper.ClusterMapper

                at org.mapstruct.factory.Mappers.getMapper(Mappers.java:75) ~[mapstruct-1.3.1.Final.jar:na]

                at org.mapstruct.factory.Mappers.getMapper(Mappers.java:58) ~[mapstruct-1.3.1.Final.jar:na]

                ... 42 common frames omitted`

Regards

GP

**Comment by germanosin** [comment]
Hi @pronzato. We are using lombok and mapstruct for annotation processing. Looks like your eclipse installation doesn't support it. Could you try to install them as plugins and try again?
