### ISSUE TITLE
Cluster : Version 0.5.0 failed to collect cluster info on old kafka versions

### ISSUE THREAD

**Issue by OranShuster** [provectus/kafka-ui#3211]
**Describe the bug** (Actual behavior)
We have a 2.0.0 kafka cluster (i know, old), using version 0.4.0 works correctly but when i upgraded to 0.5.0 i saw the following error message

```
java.lang.IllegalStateException: Error while creating AdminClient for Cluster stg
	at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3776)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default includeClusterAuthorizedOperations at version 6
```

The UI has multiple issues
Brokers - page is compeltly blank
Topics - Loads forever
Consumers - A red error popup shows with 

```
500 Internal Server Error
Error while creating AdminClient for Cluster stg
```

I can see the 0.5.0 version is using kafka 3.3.1 but 0.4.0 is using 2.8.0
i couldn't find any kafka version compatibility but i assume this is the cause of this issue

**Expected behavior**
Using a different version of kafka client according to remote version or listing supported versions in the README

**Set up**
1.Running docker image 0.5.0/0.4.0 in kubernetes cluster
2.Running 2.0.0 kafka cluster running on EC2
3.No other settings are changed

**Steps to Reproduce**
1.  run the docker image with environment variables KAFKA_CLUSTERS_0_ZOOKEEPER and KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS

**Screenshots**
None

**Additional context**
None

**Comment by Haarolean** [comment]
Hi, please try pulling `master`-labeled docker image. It's been fixed within #3141, we might do a minor release soon.
Cheers.
