### ISSUE TITLE
auth0 provider stopped working in 0.5.0

### ISSUE THREAD

**Issue by davide-malagoli** [provectus/kafka-ui#3272]
**Describe the bug** (Actual behavior)

Updating an existing Kafka UI from version 0.4.0 to 0.5.0
breaks SSO login for Keycloak.
It says that the provider is not set, but the provider is auth0

![image](https://user-images.githubusercontent.com/490521/214811087-ca28484c-d895-4c00-bf69-dbe4219d6f29.png)

We followed the guide for SSO in version 0.4.0

https://github.com/provectus/kafka-ui/blob/master/documentation/guides/SSO.md

and then updated the settings as described in the braeking changes of the 0.5.0 release,
but it does not work.

https://github.com/provectus/kafka-ui/releases/tag/v0.5.0

It is still valid in the current lastest version of docker image

**Expected behavior**
After changing the properties as described in the realse notes of 0.5.0, SSO must function correctly as before

**Set up**
We used the docker-compose as described in

https://github.com/provectus/kafka-ui/blob/master/docker-compose.md

but with image

provectuslabs/kafka-ui:v0.4.0

For keycloak, u can use this gist

https://gist.github.com/tderick/50df3b10fb00258d64315fbc8c4d39ff

using version 11.0.1

**Steps to Reproduce**

1. using docker-compose, create kafka ui and kecyloak
2. try to configure to function as described in the guide
3. update to 0.5.0
4. see the container not starting

**Additional context**

full trace of the error follows

Picked up JAVA_TOOL_OPTIONS: -Djavax.net.debug=tls
 _   _ ___    __             _                _          _  __      __ _
| | | |_ _|  / _|___ _ _    /_\  _ __ __ _ __| |_  ___  | |/ /__ _ / _| |_____
| |_| || |  |  _/ _ | '_|  / _ \| '_ / _` / _| ' \/ -_) | ' </ _` |  _| / / _`|
 \___/|___| |_| \___|_|   /_/ \_| .__\__,_\__|_||_\___| |_|\_\__,_|_| |_\_\__,|
                                 |_|                                             

[30m2023-01-26 09:52:01,553[0;39m [34mINFO [0;39m [[34mbackground-preinit[0;39m] [33mo.h.v.i.u.Version[0;39m: HV000001: Hibernate Validator 6.2.5.Final
[30m2023-01-26 09:52:01,945[0;39m [34mINFO [0;39m [[34mmain[0;39m] [33mc.p.k.u.KafkaUiApplication[0;39m: Starting KafkaUiApplication using Java 17.0.5 on kafka-ui-7c6bb7c776-cw7kb with PID 1 (/kafka-ui-api.jar started by 1000790000 in /)
[30m2023-01-26 09:52:01,955[0;39m [39mDEBUG[0;39m [[34mmain[0;39m] [33mc.p.k.u.KafkaUiApplication[0;39m: Running with Spring Boot v2.7.5, Spring v5.3.23
[30m2023-01-26 09:52:01,957[0;39m [34mINFO [0;39m [[34mmain[0;39m] [33mc.p.k.u.KafkaUiApplication[0;39m: No active profile set, falling back to 1 default profile: "default"
[30m2023-01-26 09:52:26,142[0;39m [34mINFO [0;39m [[34mmain[0;39m] [33mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m: Bean 'org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[30m2023-01-26 09:52:28,464[0;39m [31mWARN [0;39m [[34mmain[0;39m] [33mo.s.b.w.r.c.AnnotationConfigReactiveWebServerApplicationContext[0;39m: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'OAuthLogoutSuccessHandler' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/config/auth/logout/OAuthLogoutSuccessHandler.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auth.oauth2-com.provectus.kafka.ui.config.auth.OAuthProperties': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Provider name must not be empty
[30m2023-01-26 09:52:28,610[0;39m [34mINFO [0;39m [[34mmain[0;39m] [33mo.s.b.a.l.ConditionEvaluationReportLoggingListener[0;39m: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[30m2023-01-26 09:52:29,243[0;39m [1;31mERROR[0;39m [[34mmain[0;39m] [33mo.s.b.SpringApplication[0;39m: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'OAuthLogoutSuccessHandler' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/config/auth/logout/OAuthLogoutSuccessHandler.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auth.oauth2-com.provectus.kafka.ui.config.auth.OAuthProperties': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Provider name must not be empty
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.provectus.kafka.ui.KafkaUiApplication.main(KafkaUiApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auth.oauth2-com.provectus.kafka.ui.config.auth.OAuthProperties': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Provider name must not be empty
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 27 common frames omitted
Caused by: java.lang.IllegalArgumentException: Provider name must not be empty
	at org.springframework.util.Assert.hasText(Assert.java:289)
	at com.provectus.kafka.ui.config.auth.OAuthProperties.validateProvider(OAuthProperties.java:23)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at com.provectus.kafka.ui.config.auth.OAuthProperties.validate(OAuthProperties.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 40 common frames omitted

**Comment by Haarolean** [comment]
Hey, try replacing `issuer_uri` with `issuer-uri`. Please comment here if it doesn't help.

**Comment by mind-mind** [comment]
Hi, I still got the error

AUTH_TYPE: OAUTH2
    AUTH_OAUTH2_CLIENT_AUTH0_CLIENTID:
    AUTH_OAUTH2_CLIENT_AUTH0_CLIENTSECRET:
   AUTH_OAUTH2_CLIENT_AUTH0_SCOPE: 
   AUTH_OAUTH2_CLIENT_AUTH0_ISSUER-URI:

Doesn't it correct?

**Comment by Haarolean** [comment]
@mind-mind looks good, try adding `AUTH_OAUTH2_CLIENT_AUTH0_provider: auth0`?

**Comment by mind-mind** [comment]
Hm, Did you mean add

AUTH_OAUTH2_CLIENT_AUTH0_ _provider_CLIENTID:
AUTH_OAUTH2_CLIENT_AUTH0_provider_CLIENTSECRET:
AUTH_OAUTH2_CLIENT_AUTH0 _provider_SCOPE:
AUTH_OAUTH2_CLIENT_AUTH0_ provider_ISSUER-URI:

**Comment by Haarolean** [comment]
No.

```
AUTH_TYPE: OAUTH2
AUTH_OAUTH2_CLIENT_AUTH0_CLIENTID:
AUTH_OAUTH2_CLIENT_AUTH0_CLIENTSECRET:
AUTH_OAUTH2_CLIENT_AUTH0_SCOPE:
AUTH_OAUTH2_CLIENT_AUTH0_ISSUER-URI:
AUTH_OAUTH2_CLIENT_AUTH0_provider: auth0
```

**Comment by mind-mind** [comment]
works now. Thanks

**Comment by mind-mind** [comment]
It's still doesn't works. TT

**Comment by mind-mind** [comment]
Anyway, I think it works on version 0.4.0 @Haarolean

**Comment by Haarolean** [comment]
@

**Comment by eguttmastery** [comment]
I am also experiencing this issue authenticating with Azure.  Works correctly in 0.4.0, but stops functioning when upgrading to 0.5.0 and following the breaking changes.
Mine stops with `Provider name must not be empty`

**Comment by Teviwe** [comment]
> No.
> 
> ```
> AUTH_TYPE: OAUTH2
> AUTH_OAUTH2_CLIENT_AUTH0_CLIENTID:
> AUTH_OAUTH2_CLIENT_AUTH0_CLIENTSECRET:
> AUTH_OAUTH2_CLIENT_AUTH0_SCOPE:
> AUTH_OAUTH2_CLIENT_AUTH0_ISSUER-URI:
> AUTH_OAUTH2_CLIENT_AUTH0_provider: auth0
> ```


@Haarolean thanks for this example.
After adding this parameters auth0 works fine.
But for my setup need add this parameter:
`AUTH_OAUTH2_CLIENT_AUTH0_custom-params_type: auth0`
Without custom-params had errors when java app starts.

**Comment by Haarolean** [comment]
@Teviwe we'll fix that, thanks :)

**Comment by Dentling** [comment]
Thanks @Teviwe 

Adding `AUTH_OAUTH2_CLIENT_AUTH0_custom-params_type: auth0` also fixed it for me

**Comment by mind-mind** [comment]
It works for me too

**Comment by letrunghieu** [comment]
I use the `0.6.0` version and only need to add `AUTH_OAUTH2_CLIENT_AUTH0_PROVIDER: auth0` environment variable. The `AUTH_OAUTH2_CLIENT_AUTH0_custom-params_type: auth0` variable is not required for me.

**Comment by mindman21** [comment]
Azure Ad is not work anymore it doesn't trigger.
It running, but doesn't work. I'm using version 6

**Comment by piermotte** [comment]
Thanks a lot @letrunghieu, It also works for me on `0.6.0` with `AUTH_OAUTH2_CLIENT_AUTH0_PROVIDER: auth0`

**Comment by Dugong42** [comment]
I've just submitted a documentation PR about the configuration of Keycloak as OIDC provider : #3863

**Comment by Haarolean** [comment]
The part with the required "type" custom param must've been fixed previously.
