### ISSUE TITLE
InstanceAlreadyExistsException

### ISSUE THREAD

**Issue by cassanellicarlo** [provectus/kafka-ui#3323]
**Describe the bug** (Actual behavior)

With a newer version of kafka-ui, i cannot start the container. I get WARN  [parallel-1] o.a.k.c.u.AppInfoParser: Error registering AppInfo mbean javax.management.InstanceAlreadyExistsException: kafka.admin.client:type=app-info,id=kafka-ui-admin-client-1675866213882

In version 0.4 it used to work correctly

When i open the browser at localhost:8080, the loading spinner appears and then i get a white page.

**Expected behavior**

The application should start up correctly

**Set up**

1. App version (docker image version or check commit hash in the top left corner in UI): latest

**Steps to Reproduce**

podman run -it \
    --volume=truststore_BN_CA.jks:/opt/kafka/config/truststore.jks:U \
    --volume=$TICKET_LOCATION:/tmp/krb5cc_100:U \
    --volume=krb5.conf:/etc/krb5.conf:U \
    --env KAFKA_CLUSTERS_0_NAME='DC1' \
    --env KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=$BOOTSTRAP_SERVERS_DC1 \
    --env KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL='SASL_SSL' \
    --env KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM='GSSAPI' \
    --env KAFKA_CLUSTERS_0_PROPERTIES_SASL_KERBEROS_SERVICE_NAME='kafka' \
    --env KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG='com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true;' \
    --env KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION='/opt/kafka/config/truststore.jks' \
    --env KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD='***' \
    --env KAFKA_CLUSTERS_1_NAME='DC2' \
    --env KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=$BOOTSTRAP_SERVERS_DC2 \
    --env KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL='SASL_SSL' \
    --env KAFKA_CLUSTERS_1_PROPERTIES_SASL_MECHANISM='GSSAPI' \
    --env KAFKA_CLUSTERS_1_PROPERTIES_SASL_KERBEROS_SERVICE_NAME='kafka' \
    --env KAFKA_CLUSTERS_1_PROPERTIES_SASL_JAAS_CONFIG='com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true;' \
    --env KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_LOCATION='/opt/kafka/config/truststore.jks' \
    --env KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_PASSWORD='truststore' \
    --publish 8080:8080 \
    kafka-ui:latest

**Additional context**

2023-02-08 14:23:34,172 WARN  [parallel-1] o.a.k.c.a.AdminClientConfig: These configurations '[sasl.kerberos.service.name]' were supplied but are not used yet.
2023-02-08 14:23:34,174 INFO  [parallel-2] o.a.k.c.u.AppInfoParser: Kafka version: 3.3.1
2023-02-08 14:23:34,174 INFO  [parallel-2] o.a.k.c.u.AppInfoParser: Kafka commitId: e23c59d00e687ff5
2023-02-08 14:23:34,174 INFO  [parallel-2] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1675866214172
2023-02-08 14:23:34,178 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka version: 3.3.1
2023-02-08 14:23:34,178 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka commitId: e23c59d00e687ff5
2023-02-08 14:23:34,178 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1675866214173
2023-02-08 14:23:34,181 WARN  [parallel-1] o.a.k.c.u.AppInfoParser: Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.admin.client:type=app-info,id=kafka-ui-admin-client-1675866213882
        at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1865)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:960)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:895)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
        at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:523)
        at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:64)
        at org.apache.kafka.clients.admin.KafkaAdminClient.<init>(KafkaAdminClient.java:604)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:546)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:485)
        at org.apache.kafka.clients.admin.Admin.create(Admin.java:134)
        at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
        at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$2(AdminClientServiceImpl.java:41)
        at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:86)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4440)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
        at reactor.core.publisher.Operators.complete(Operators.java:137)
        at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-08 14:23:35,382 DEBUG [parallel-4] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: DC1
2023-02-08 14:23:35,387 DEBUG [parallel-2] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: DC2

**Comment by Haarolean** [comment]
@cassanellicarlo make sure you don't have any previous containers with kafka-ui running as well

**Comment by cassanellicarlo** [comment]
Hello, thanks for you answers.

- is this issue persistent (appears on each start)? yes, seems so. I'm running the podman containers with the --rm flag so they are removed after exit.
- have you tried to reload page after some time (say, 30 seconds after startup)? yes, but it doesn't work.

I've tried again with version v0.4.0 and it's working correctly. Not with the latest version. Inspecting the developer console, that's what i found. Could it be related?

latest
![image](https://user-images.githubusercontent.com/25034584/218746821-f8dd4700-5e0d-4462-91d6-6a659d2c1ded.png)


version 0.4.0
![image](https://user-images.githubusercontent.com/25034584/218747193-458e7707-7cec-4e53-bf39-dc13128f063f.png)

**Comment by Haarolean** [comment]
@cassanellicarlo does this pc have an access to the internet?

**Comment by Haarolean** [comment]
@cassanellicarlo can you confirm it works fine without authentication?

**Comment by Haarolean** [comment]
Do you mean you can't try or it doesn't work w/o auth as well?

**Comment by cassanellicarlo** [comment]
I can't try atm.

**Comment by cassanellicarlo** [comment]
I think some resources are blocked by the company proxy, but with version 0.4.0 it works

**Comment by Haarolean** [comment]
There are just a few external calls:
1) github version check via github API, which is visible on your screenshots (to be fixed within #2753)
2) Some google fonts fetching (yet to be done within #2728)

**Comment by yoyehan** [comment]
Hi @Haarolean!
I'm facing a same issue where external calls to 
`https://api.github.com/repos/provectus/kafka-ui/releases/latest `
is causing the entire page to not load. It worked fine one 0.4.0, and stopped working on 0.5.0 and 0.6.0.
The company is behind the firewall and cannot access these public domains btw.

I think the addition of [checking latest version](https://github.com/provectus/kafka-ui/blob/v0.5.0/kafka-ui-react-app/src/lib/hooks/api/latestVersion.ts) is messing with the UI.

**Comment by Haarolean** [comment]
#2753 Fixed within 0.7.0
CORS issue: #3401

Closing as this has became some dump for unrelated issues
