### ISSUE TITLE
"send message" fails in constrained cluster

### ISSUE THREAD

**Issue by moinmoin** [provectus/kafka-ui#3414]
**Describe the bug** (Actual behavior)
Sending a message to a topic fails. It works with different tools.
Reading from the topic works since issue #1452 was resolved.

**Expected behavior**
Message should be written to topic.

**Set up**
The following permissions are granted in the contrained cluster.

- Only a few topics are granted (read / write)
- DESCRIBE CLUSTER was granted for a test, but the issue was still there. 
- Reading from topics works with the permissions listed below.

```
Permission |    Operation     | ResourceType | ResourceName  | PatternType
------------+------------------+--------------+---------------+--------------
 ALLOW      | READ             | TOPIC        | <some topics> | LITERAL
 ALLOW      | DESCRIBE_CONFIGS | TOPIC        | <some topics> | LITERAL
 ALLOW      | DESCRIBE         | GROUP        | *             | LITERAL
 ALLOW      | DESCRIBE_CONFIGS | CLUSTER      | kafka-cluster | LITERAL
```

Log:
```
[30m2023-02-27 13:11:09,121[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.p.ProducerConfig[0;39m: ProducerConfig values: 
	acks = -1
	batch.size = 16384
	bootstrap.servers = [host1:6668, host2:6668, host3:6668]
	buffer.memory = 33554432
	client.dns.lookup = use_all_dns_ips
	client.id = producer-1
	compression.type = none
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 120000
	enable.idempotence = true
	interceptor.classes = []
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metadata.max.idle.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.adaptive.partitioning.enable = true
	partitioner.availability.timeout.ms = 0
	partitioner.class = null
	partitioner.ignore.keys = false
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.connect.timeout.ms = null
	sasl.login.read.timeout.ms = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = GSSAPI
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = SASL_SSL
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = /mycerts/cacerts
	ssl.truststore.password = [hidden]
	ssl.truststore.type = jks
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer

[30m2023-02-27 13:11:09,130[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.p.KafkaProducer[0;39m: [Producer clientId=producer-1] Instantiated an idempotent producer.
[30m2023-02-27 13:11:09,197[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.u.AppInfoParser[0;39m: Kafka version: 3.3.1
[30m2023-02-27 13:11:09,197[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.u.AppInfoParser[0;39m: Kafka commitId: e23c59d00e687ff5
[30m2023-02-27 13:11:09,197[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.u.AppInfoParser[0;39m: Kafka startTimeMs: 1677499869197
[30m2023-02-27 13:11:09,271[0;39m [34mINFO [0;39m [[34mkafka-producer-network-thread | producer-1[0;39m] [33mo.a.k.c.Metadata[0;39m: [Producer clientId=producer-1] Cluster ID: JNk-WIniTtGTLX965I7ynw
[30m2023-02-27 13:11:09,288[0;39m [34mINFO [0;39m [[34mkafka-producer-network-thread | producer-1[0;39m] [33mo.a.k.c.p.i.TransactionManager[0;39m: [Producer clientId=producer-1] Transiting to fatal error state due to org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
[30m2023-02-27 13:11:09,300[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.p.KafkaProducer[0;39m: [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
[30m2023-02-27 13:11:09,303[0;39m [1;31mERROR[0;39m [[34mkafka-producer-network-thread | producer-1[0;39m] [33mo.a.k.c.p.i.Sender[0;39m: [Producer clientId=producer-1] Aborting producer batches due to fatal error
org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
[30m2023-02-27 13:11:09,408[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.m.Metrics[0;39m: Metrics scheduler closed
[30m2023-02-27 13:11:09,408[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.m.Metrics[0;39m: Closing reporter org.apache.kafka.common.metrics.JmxReporter
[30m2023-02-27 13:11:09,409[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.m.Metrics[0;39m: Metrics reporters closed
[30m2023-02-27 13:11:09,409[0;39m [34mINFO [0;39m [[34mboundedElastic-2[0;39m] [33mo.a.k.c.u.AppInfoParser[0;39m: App info kafka.producer for producer-1 unregistered
[30m2023-02-27 13:11:09,429[0;39m [1;31mERROR[0;39m [[34mboundedElastic-2[0;39m] [33mo.s.b.a.w.r.e.AbstractErrorWebExceptionHandler[0;39m: [11c0db7b-47]  500 Server Error for HTTP POST "/api/clusters/kafkacluster/topics/topic.hello.world/messages"
org.apache.kafka.common.KafkaException: Cannot execute transactional method because we are in an error state
	at org.apache.kafka.clients.producer.internals.TransactionManager.maybeFailWithError(TransactionManager.java:1010)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Handler com.provectus.kafka.ui.controller.MessagesController#sendTopicMessages(String, String, Mono, ServerWebExchange) [DispatcherHandler]
	*__checkpoint ? com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
	*__checkpoint ? com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.ui.LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP POST "/api/clusters/kafkacluster/topics/topic.hello.world/messages" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.apache.kafka.clients.producer.internals.TransactionManager.maybeFailWithError(TransactionManager.java:1010)
		at org.apache.kafka.clients.producer.internals.TransactionManager.maybeAddPartition(TransactionManager.java:328)
		at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:1048)
		at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:949)
		at com.provectus.kafka.ui.service.MessagesService.sendMessageImpl(MessagesService.java:124)
		at com.provectus.kafka.ui.service.MessagesService.lambda$sendMessage$8(MessagesService.java:92)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
		at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
```

**Comment by iliax** [comment]
Hello @moinmoin, thank you for an issue, this is important case for us. 

Since kafka client [v3.2.0](https://kafka.apache.org/documentation/#upgrade_320_notable) `enable.idempotence` property is `true` by default for all producers (for kafka-ui producers also). 

Considering that, you have 2 options to make producing work:
1. Allow user to make idempotent write via [ACL](https://docs.confluent.io/platform/current/kafka/authorization.html#enabling-authorization-for-idempotent-and-transactional-apis). 
2. Disable idempotent write in kafka-ui producer by setting `enable.idempotence` property cluster property to `false.` (ex. set `KAFKA_CLUSTERS_0_PROPERTIES_ENABLE_IDEMPOTENCE` env var to `false`).

**Comment by moinmoin** [comment]
@iliax thank you! that solved the problem. I could send successfully a message to a cluster v2.5
