### ISSUE TITLE
Protobuf Deserialization: Initializing Protobuf message types fails when loading multiple Proto files

### ISSUE THREAD

**Issue by joschi** [provectus/kafka-ui#3463]
**Describe the bug** (Actual behavior)

When enabling Protobuf support in Kafka UI as described in https://github.com/provectus/kafka-ui/blob/4d20cb6/documentation/guides/Protobuf.md, Kafka UI fails to start if one of the Protobuf files references a type with a leading dot (see reference in Additional Context) with the following stack trace (see Additional Context for full stack trace):

```
Caused by: java.lang.IllegalStateException: com.google.protobuf.Descriptors$DescriptorValidationException: my.package.HourlySalaryOverride.Changed.effectiveDate: ".my.package.protocgenerated.Date" is not defined.
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDynamicSchema(ProtobufSchema.java:1320)
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDynamicSchema(ProtobufSchema.java:1150)
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDynamicSchema(ProtobufSchema.java:1142)
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDescriptor(ProtobufSchema.java:1104)
	at com.provectus.kafka.ui.serdes.builtin.ProtobufFileSerde$Configuration.lambda$getDescriptorAndPath$7(ProtobufFileSerde.java:258)
```

**Expected behavior**

Kafka UI should start without an error if one of the Protobuf files contains a type reference with leading dot.

**Set up**

- Kafka UI version: 4d20cb695804d4247731dffc62ebdb5d685647be via the [corresponding Docker image](https://hub.docker.com/layers/provectuslabs/kafka-ui/4d20cb695804d4247731dffc62ebdb5d685647be/images/sha256-2785631f4279f66a2d0da23d978b9722192891c5cfca3d8de238e135736a8764?context=explore).
- Runtime environment: Kubernetes, no Helm chart.
- Configuration file (via environment variable `SPRING_CONFIG_LOCATION=file:/path/to/config.yaml`):
```
auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: [REDACTED]
    name: my-kafka-cluster
    properties:
      # AWS SASL IAM settings [...]
    protobufFiles:
    - /path/to/my/package/hourly-salary-override.proto
    - /path/to/my/package/date.proto
    protobufMessageNameByTopic:
      "my.topic": "my.package.HourlySalaryOverride"
    readOnly: true
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
  health:
    ldap:
      enabled: false
```

**Steps to Reproduce**

```
# ls --tree protobuf-bug/
protobuf-bug
├── config.yaml
├── docker-compose.yaml
├── protobuf
│   └── my
│       └── package
│           ├── date.proto
│           └── hourly-salary-override.proto
└── scripts
    └── update_run.sh
```
[protobuf-bug.zip](https://github.com/provectus/kafka-ui/files/10921130/protobuf-bug.zip)

**Additional context**

> A leading ‘.’ (for example, `.foo.bar.Baz`) means to start from the outermost scope instead.

Source: https://protobuf.dev/programming-guides/proto3/#packages-and-name-resolution

### Protobuf files
`my/package/hourly-salary-override.proto`
```
syntax = "proto3";

package my.package;

import "my/package/date.proto";

message HourlySalaryOverride {
    message Changed {
        .my.package.protocgenerated.Date effectiveDate = 1;
    }
}
```

`my/package/date.proto`:
```
syntax = "proto3";

package my.package.protocgenerated;

message Date {
    int32 year = 1;
    int32 month = 2;
    int32 day = 3;
}
```

The Protobuf files are valid and can be processed by `protoc`:
```
# protoc protobuf/my/package/* --proto_path=protobuf/ --java_out=test
# ls --tree test/
test
└── my
    └── package
        ├── HourlySalaryOverrideOuterClass.java
        └── protocgenerated
            └── DateOuterClass.java
```

<details>
<summary>Full stack trace</summary>

```text
2023-03-08 10:48:04,303 ERROR [main] o.s.b.SpringApplication: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messagesService' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/service/MessagesService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'deserializationService' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/service/DeserializationService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.provectus.kafka.ui.service.DeserializationService]: Constructor threw exception; nested exception is java.lang.IllegalStateException: com.google.protobuf.Descriptors$DescriptorValidationException: my.package.HourlySalaryOverride.Changed.effectiveDate: ".my.package.protocgenerated.Date" is not defined.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.provectus.kafka.ui.KafkaUiApplication.main(KafkaUiApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'deserializationService' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/service/DeserializationService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.provectus.kafka.ui.service.DeserializationService]: Constructor threw exception; nested exception is java.lang.IllegalStateException: com.google.protobuf.Descriptors$DescriptorValidationException: my.package.HourlySalaryOverride.Changed.effectiveDate: ".my.package.protocgenerated.Date" is not defined.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.provectus.kafka.ui.service.DeserializationService]: Constructor threw exception; nested exception is java.lang.IllegalStateException: com.google.protobuf.Descriptors$DescriptorValidationException: my.package.HourlySalaryOverride.Changed.effectiveDate: ".my.package.protocgenerated.Date" is not defined.
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
	... 41 common frames omitted
Caused by: java.lang.IllegalStateException: com.google.protobuf.Descriptors$DescriptorValidationException: my.package.HourlySalaryOverride.Changed.effectiveDate: ".my.package.protocgenerated.Date" is not defined.
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDynamicSchema(ProtobufSchema.java:1320)
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDynamicSchema(ProtobufSchema.java:1150)
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDynamicSchema(ProtobufSchema.java:1142)
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDescriptor(ProtobufSchema.java:1104)
	at com.provectus.kafka.ui.serdes.builtin.ProtobufFileSerde$Configuration.lambda$getDescriptorAndPath$7(ProtobufFileSerde.java:258)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.HashMap$EntrySpliterator.tryAdvance(HashMap.java:1871)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.provectus.kafka.ui.serdes.builtin.ProtobufFileSerde$Configuration.getDescriptorAndPath(ProtobufFileSerde.java:260)
	at com.provectus.kafka.ui.serdes.builtin.ProtobufFileSerde$Configuration.lambda$addProtobufSchemas$16(ProtobufFileSerde.java:311)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.provectus.kafka.ui.serdes.builtin.ProtobufFileSerde$Configuration.addProtobufSchemas(ProtobufFileSerde.java:312)
	at com.provectus.kafka.ui.serdes.builtin.ProtobufFileSerde$Configuration.lambda$create$3(ProtobufFileSerde.java:235)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.provectus.kafka.ui.serdes.builtin.ProtobufFileSerde$Configuration.create(ProtobufFileSerde.java:235)
	at com.provectus.kafka.ui.serdes.builtin.ProtobufFileSerde.autoConfigure(ProtobufFileSerde.java:96)
	at com.provectus.kafka.ui.serdes.SerdesInitializer.autoConfigureSerde(SerdesInitializer.java:195)
	at com.provectus.kafka.ui.serdes.SerdesInitializer.lambda$init$0(SerdesInitializer.java:113)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at com.provectus.kafka.ui.serdes.SerdesInitializer.init(SerdesInitializer.java:110)
	at com.provectus.kafka.ui.service.DeserializationService.<init>(DeserializationService.java:40)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 43 common frames omitted
Caused by: com.google.protobuf.Descriptors$DescriptorValidationException: my.package.HourlySalaryOverride.Changed.effectiveDate: ".my.package.protocgenerated.Date" is not defined.
	at com.google.protobuf.Descriptors$DescriptorPool.lookupSymbol(Descriptors.java:2562)
	at com.google.protobuf.Descriptors$FieldDescriptor.crossLink(Descriptors.java:1559)
	at com.google.protobuf.Descriptors$FieldDescriptor.access$1400(Descriptors.java:1057)
	at com.google.protobuf.Descriptors$Descriptor.crossLink(Descriptors.java:1000)
	at com.google.protobuf.Descriptors$Descriptor.crossLink(Descriptors.java:996)
	at com.google.protobuf.Descriptors$Descriptor.access$1200(Descriptors.java:648)
	at com.google.protobuf.Descriptors$FileDescriptor.crossLink(Descriptors.java:600)
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:321)
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:289)
	at io.confluent.kafka.schemaregistry.protobuf.dynamic.DynamicSchema.init(DynamicSchema.java:290)
	at io.confluent.kafka.schemaregistry.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:224)
	at io.confluent.kafka.schemaregistry.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:55)
	at io.confluent.kafka.schemaregistry.protobuf.dynamic.DynamicSchema$Builder.build(DynamicSchema.java:385)
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.toDynamicSchema(ProtobufSchema.java:1318)
	... 83 common frames omitted
```

**Comment by joschi** [comment]
This seems to be working with the new `protobufFilesDir` configuration property, but unfortunately we have multiple Protobuf "roots" coming from multiple different Git repositories with conflicting file names (but not message types). 🤔

**Comment by joschi** [comment]
@iliax Thanks for your suggestion!

Unfortunately this also doesn't work in our case because of the (sub-optimal) split of Protobuf message declarations across multiple repositories. For example, we have some repositories referring to Protobuf files and message types from other repositories.

Yes, it's horrible and hopefully won't last much longer in favor of a real Schema Registry. 😅

**Comment by Haarolean** [comment]
>Yes, it's horrible and hopefully won't last much longer in favor of a real Schema Registry. 😅
I suppose this sums up the topic :) Since you already maintain a fork, I guess you could implement this temporarily solution until you move to a real SR.
