### ISSUE TITLE
Error while creating AdminClient for Cluster on Kafka 1.1.1

### ISSUE THREAD

**Issue by robsonpeixoto** [provectus/kafka-ui#3472]
**Describe the bug** (Actual behavior)

Fail when try to connect on Kafka 1.1.1.

**Expected behavior**

Access with success.

**Set up**

Follow the `docker-compose.yml`
```yaml
version: "3.8"

services:
  zookeeper:
    image: zookeeper:3.4.10
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:4.1.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://127.0.0.1:9092
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      TOPIC_AUTO_CREATE: 1
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:19092" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
    depends_on:
      - kafka
```

**Steps to Reproduce**

1. docker-compose up

**Screenshots**

![image](https://user-images.githubusercontent.com/124390/224100300-bd261fbe-bbec-41c8-8495-1953ac2eb3be.png)

**Additional context**

Log:

```
❯ docker compose logs kafka-ui
kafka-ui-kafka-ui-1  |  _   _ ___    __             _                _          _  __      __ _
kafka-ui-kafka-ui-1  | | | | |_ _|  / _|___ _ _    /_\  _ __ __ _ __| |_  ___  | |/ /__ _ / _| |_____
kafka-ui-kafka-ui-1  | | |_| || |  |  _/ _ | '_|  / _ \| '_ / _` / _| ' \/ -_) | ' </ _` |  _| / / _`|
kafka-ui-kafka-ui-1  |  \___/|___| |_| \___|_|   /_/ \_| .__\__,_\__|_||_\___| |_|\_\__,_|_| |_\_\__,|
kafka-ui-kafka-ui-1  |                                  |_|                                             
kafka-ui-kafka-ui-1  | 
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:12,892 INFO  [background-preinit] o.h.v.i.u.Version: HV000001: Hibernate Validator 6.2.5.Final
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:12,925 INFO  [main] c.p.k.u.KafkaUiApplication: Starting KafkaUiApplication using Java 17.0.5 on f51cd795541c with PID 1 (/kafka-ui-api.jar started by kafkaui in /)
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:12,926 DEBUG [main] c.p.k.u.KafkaUiApplication: Running with Spring Boot v2.7.5, Spring v5.3.23
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:12,926 INFO  [main] c.p.k.u.KafkaUiApplication: No active profile set, falling back to 1 default profile: "default"
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:15,632 DEBUG [main] c.p.k.u.s.SerdesInitializer: Configuring serdes for cluster local
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:16,434 INFO  [main] o.s.b.a.e.w.EndpointLinksResolver: Exposing 2 endpoint(s) beneath base path '/actuator'
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:16,717 INFO  [main] o.s.b.a.s.r.ReactiveUserDetailsServiceAutoConfiguration: 
kafka-ui-kafka-ui-1  | 
kafka-ui-kafka-ui-1  | Using generated security password: 3455aaa9-61bf-4096-99e5-5c100908aec0
kafka-ui-kafka-ui-1  | 
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:16,891 WARN  [main] c.p.k.u.c.a.DisabledAuthSecurityConfig: Authentication is disabled. Access will be unrestricted.
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:17,613 INFO  [main] o.s.b.w.e.n.NettyWebServer: Netty started on port 8080
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:17,635 INFO  [main] c.p.k.u.KafkaUiApplication: Started KafkaUiApplication in 5.5 seconds (JVM running for 6.128)
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:17,671 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: local
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:17,690 INFO  [parallel-1] o.a.k.c.a.AdminClientConfig: AdminClientConfig values: 
kafka-ui-kafka-ui-1  | 	bootstrap.servers = [kafka:19092]
kafka-ui-kafka-ui-1  | 	client.dns.lookup = use_all_dns_ips
kafka-ui-kafka-ui-1  | 	client.id = kafka-ui-admin-client-1678374977679
kafka-ui-kafka-ui-1  | 	connections.max.idle.ms = 300000
kafka-ui-kafka-ui-1  | 	default.api.timeout.ms = 60000
kafka-ui-kafka-ui-1  | 	metadata.max.age.ms = 300000
kafka-ui-kafka-ui-1  | 	metric.reporters = []
kafka-ui-kafka-ui-1  | 	metrics.num.samples = 2
kafka-ui-kafka-ui-1  | 	metrics.recording.level = INFO
kafka-ui-kafka-ui-1  | 	metrics.sample.window.ms = 30000
kafka-ui-kafka-ui-1  | 	receive.buffer.bytes = 65536
kafka-ui-kafka-ui-1  | 	reconnect.backoff.max.ms = 1000
kafka-ui-kafka-ui-1  | 	reconnect.backoff.ms = 50
kafka-ui-kafka-ui-1  | 	request.timeout.ms = 30000
kafka-ui-kafka-ui-1  | 	retries = 2147483647
kafka-ui-kafka-ui-1  | 	retry.backoff.ms = 100
kafka-ui-kafka-ui-1  | 	sasl.client.callback.handler.class = null
kafka-ui-kafka-ui-1  | 	sasl.jaas.config = null
kafka-ui-kafka-ui-1  | 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
kafka-ui-kafka-ui-1  | 	sasl.kerberos.min.time.before.relogin = 60000
kafka-ui-kafka-ui-1  | 	sasl.kerberos.service.name = null
kafka-ui-kafka-ui-1  | 	sasl.kerberos.ticket.renew.jitter = 0.05
kafka-ui-kafka-ui-1  | 	sasl.kerberos.ticket.renew.window.factor = 0.8
kafka-ui-kafka-ui-1  | 	sasl.login.callback.handler.class = null
kafka-ui-kafka-ui-1  | 	sasl.login.class = null
kafka-ui-kafka-ui-1  | 	sasl.login.connect.timeout.ms = null
kafka-ui-kafka-ui-1  | 	sasl.login.read.timeout.ms = null
kafka-ui-kafka-ui-1  | 	sasl.login.refresh.buffer.seconds = 300
kafka-ui-kafka-ui-1  | 	sasl.login.refresh.min.period.seconds = 60
kafka-ui-kafka-ui-1  | 	sasl.login.refresh.window.factor = 0.8
kafka-ui-kafka-ui-1  | 	sasl.login.refresh.window.jitter = 0.05
kafka-ui-kafka-ui-1  | 	sasl.login.retry.backoff.max.ms = 10000
kafka-ui-kafka-ui-1  | 	sasl.login.retry.backoff.ms = 100
kafka-ui-kafka-ui-1  | 	sasl.mechanism = GSSAPI
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.clock.skew.seconds = 30
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.expected.audience = null
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.expected.issuer = null
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.jwks.endpoint.url = null
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.scope.claim.name = scope
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.sub.claim.name = sub
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.token.endpoint.url = null
kafka-ui-kafka-ui-1  | 	security.protocol = PLAINTEXT
kafka-ui-kafka-ui-1  | 	security.providers = null
kafka-ui-kafka-ui-1  | 	send.buffer.bytes = 131072
kafka-ui-kafka-ui-1  | 	socket.connection.setup.timeout.max.ms = 30000
kafka-ui-kafka-ui-1  | 	socket.connection.setup.timeout.ms = 10000
kafka-ui-kafka-ui-1  | 	ssl.cipher.suites = null
kafka-ui-kafka-ui-1  | 	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
kafka-ui-kafka-ui-1  | 	ssl.endpoint.identification.algorithm = https
kafka-ui-kafka-ui-1  | 	ssl.engine.factory.class = null
kafka-ui-kafka-ui-1  | 	ssl.key.password = null
kafka-ui-kafka-ui-1  | 	ssl.keymanager.algorithm = SunX509
kafka-ui-kafka-ui-1  | 	ssl.keystore.certificate.chain = null
kafka-ui-kafka-ui-1  | 	ssl.keystore.key = null
kafka-ui-kafka-ui-1  | 	ssl.keystore.location = null
kafka-ui-kafka-ui-1  | 	ssl.keystore.password = null
kafka-ui-kafka-ui-1  | 	ssl.keystore.type = JKS
kafka-ui-kafka-ui-1  | 	ssl.protocol = TLSv1.3
kafka-ui-kafka-ui-1  | 	ssl.provider = null
kafka-ui-kafka-ui-1  | 	ssl.secure.random.implementation = null
kafka-ui-kafka-ui-1  | 	ssl.trustmanager.algorithm = PKIX
kafka-ui-kafka-ui-1  | 	ssl.truststore.certificates = null
kafka-ui-kafka-ui-1  | 	ssl.truststore.location = null
kafka-ui-kafka-ui-1  | 	ssl.truststore.password = null
kafka-ui-kafka-ui-1  | 	ssl.truststore.type = JKS
kafka-ui-kafka-ui-1  | 
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:17,773 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka version: 3.3.1
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:17,773 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka commitId: e23c59d00e687ff5
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:17,773 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1678374977772
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:18,164 ERROR [parallel-1] c.p.k.u.s.StatisticsService: Failed to collect cluster local info
kafka-ui-kafka-ui-1  | java.lang.IllegalStateException: Error while creating AdminClient for Cluster local
kafka-ui-kafka-ui-1  | 	at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3776)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
kafka-ui-kafka-ui-1  | 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
kafka-ui-kafka-ui-1  | 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
kafka-ui-kafka-ui-1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka-ui-kafka-ui-1  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
kafka-ui-kafka-ui-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
kafka-ui-kafka-ui-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
kafka-ui-kafka-ui-1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
kafka-ui-kafka-ui-1  | Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default includeClusterAuthorizedOperations at version 5
kafka-ui-kafka-ui-1  | 2023-03-09 15:16:18,166 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: local
kafka-ui-kafka-ui-1  |  _   _ ___    __             _                _          _  __      __ _
kafka-ui-kafka-ui-1  | | | | |_ _|  / _|___ _ _    /_\  _ __ __ _ __| |_  ___  | |/ /__ _ / _| |_____
kafka-ui-kafka-ui-1  | | |_| || |  |  _/ _ | '_|  / _ \| '_ / _` / _| ' \/ -_) | ' </ _` |  _| / / _`|
kafka-ui-kafka-ui-1  |  \___/|___| |_| \___|_|   /_/ \_| .__\__,_\__|_||_\___| |_|\_\__,_|_| |_\_\__,|
kafka-ui-kafka-ui-1  |                                  |_|                                             
kafka-ui-kafka-ui-1  | 
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:34,084 INFO  [background-preinit] o.h.v.i.u.Version: HV000001: Hibernate Validator 6.2.5.Final
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:34,094 INFO  [main] c.p.k.u.KafkaUiApplication: Starting KafkaUiApplication using Java 17.0.5 on f51cd795541c with PID 1 (/kafka-ui-api.jar started by kafkaui in /)
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:34,094 DEBUG [main] c.p.k.u.KafkaUiApplication: Running with Spring Boot v2.7.5, Spring v5.3.23
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:34,095 INFO  [main] c.p.k.u.KafkaUiApplication: No active profile set, falling back to 1 default profile: "default"
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:36,052 DEBUG [main] c.p.k.u.s.SerdesInitializer: Configuring serdes for cluster local
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:36,526 INFO  [main] o.s.b.a.e.w.EndpointLinksResolver: Exposing 2 endpoint(s) beneath base path '/actuator'
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:36,648 INFO  [main] o.s.b.a.s.r.ReactiveUserDetailsServiceAutoConfiguration: 
kafka-ui-kafka-ui-1  | 
kafka-ui-kafka-ui-1  | Using generated security password: c4fc6172-8b07-4d42-bf57-de491ea5b53a
kafka-ui-kafka-ui-1  | 
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:36,739 WARN  [main] c.p.k.u.c.a.DisabledAuthSecurityConfig: Authentication is disabled. Access will be unrestricted.
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:37,214 INFO  [main] o.s.b.w.e.n.NettyWebServer: Netty started on port 8080
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:37,233 INFO  [main] c.p.k.u.KafkaUiApplication: Started KafkaUiApplication in 3.626 seconds (JVM running for 4.133)
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:37,260 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: local
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:37,277 INFO  [parallel-1] o.a.k.c.a.AdminClientConfig: AdminClientConfig values: 
kafka-ui-kafka-ui-1  | 	bootstrap.servers = [kafka:19092]
kafka-ui-kafka-ui-1  | 	client.dns.lookup = use_all_dns_ips
kafka-ui-kafka-ui-1  | 	client.id = kafka-ui-admin-client-1678381237267
kafka-ui-kafka-ui-1  | 	connections.max.idle.ms = 300000
kafka-ui-kafka-ui-1  | 	default.api.timeout.ms = 60000
kafka-ui-kafka-ui-1  | 	metadata.max.age.ms = 300000
kafka-ui-kafka-ui-1  | 	metric.reporters = []
kafka-ui-kafka-ui-1  | 	metrics.num.samples = 2
kafka-ui-kafka-ui-1  | 	metrics.recording.level = INFO
kafka-ui-kafka-ui-1  | 	metrics.sample.window.ms = 30000
kafka-ui-kafka-ui-1  | 	receive.buffer.bytes = 65536
kafka-ui-kafka-ui-1  | 	reconnect.backoff.max.ms = 1000
kafka-ui-kafka-ui-1  | 	reconnect.backoff.ms = 50
kafka-ui-kafka-ui-1  | 	request.timeout.ms = 30000
kafka-ui-kafka-ui-1  | 	retries = 2147483647
kafka-ui-kafka-ui-1  | 	retry.backoff.ms = 100
kafka-ui-kafka-ui-1  | 	sasl.client.callback.handler.class = null
kafka-ui-kafka-ui-1  | 	sasl.jaas.config = null
kafka-ui-kafka-ui-1  | 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
kafka-ui-kafka-ui-1  | 	sasl.kerberos.min.time.before.relogin = 60000
kafka-ui-kafka-ui-1  | 	sasl.kerberos.service.name = null
kafka-ui-kafka-ui-1  | 	sasl.kerberos.ticket.renew.jitter = 0.05
kafka-ui-kafka-ui-1  | 	sasl.kerberos.ticket.renew.window.factor = 0.8
kafka-ui-kafka-ui-1  | 	sasl.login.callback.handler.class = null
kafka-ui-kafka-ui-1  | 	sasl.login.class = null
kafka-ui-kafka-ui-1  | 	sasl.login.connect.timeout.ms = null
kafka-ui-kafka-ui-1  | 	sasl.login.read.timeout.ms = null
kafka-ui-kafka-ui-1  | 	sasl.login.refresh.buffer.seconds = 300
kafka-ui-kafka-ui-1  | 	sasl.login.refresh.min.period.seconds = 60
kafka-ui-kafka-ui-1  | 	sasl.login.refresh.window.factor = 0.8
kafka-ui-kafka-ui-1  | 	sasl.login.refresh.window.jitter = 0.05
kafka-ui-kafka-ui-1  | 	sasl.login.retry.backoff.max.ms = 10000
kafka-ui-kafka-ui-1  | 	sasl.login.retry.backoff.ms = 100
kafka-ui-kafka-ui-1  | 	sasl.mechanism = GSSAPI
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.clock.skew.seconds = 30
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.expected.audience = null
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.expected.issuer = null
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.jwks.endpoint.url = null
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.scope.claim.name = scope
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.sub.claim.name = sub
kafka-ui-kafka-ui-1  | 	sasl.oauthbearer.token.endpoint.url = null
kafka-ui-kafka-ui-1  | 	security.protocol = PLAINTEXT
kafka-ui-kafka-ui-1  | 	security.providers = null
kafka-ui-kafka-ui-1  | 	send.buffer.bytes = 131072
kafka-ui-kafka-ui-1  | 	socket.connection.setup.timeout.max.ms = 30000
kafka-ui-kafka-ui-1  | 	socket.connection.setup.timeout.ms = 10000
kafka-ui-kafka-ui-1  | 	ssl.cipher.suites = null
kafka-ui-kafka-ui-1  | 	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
kafka-ui-kafka-ui-1  | 	ssl.endpoint.identification.algorithm = https
kafka-ui-kafka-ui-1  | 	ssl.engine.factory.class = null
kafka-ui-kafka-ui-1  | 	ssl.key.password = null
kafka-ui-kafka-ui-1  | 	ssl.keymanager.algorithm = SunX509
kafka-ui-kafka-ui-1  | 	ssl.keystore.certificate.chain = null
kafka-ui-kafka-ui-1  | 	ssl.keystore.key = null
kafka-ui-kafka-ui-1  | 	ssl.keystore.location = null
kafka-ui-kafka-ui-1  | 	ssl.keystore.password = null
kafka-ui-kafka-ui-1  | 	ssl.keystore.type = JKS
kafka-ui-kafka-ui-1  | 	ssl.protocol = TLSv1.3
kafka-ui-kafka-ui-1  | 	ssl.provider = null
kafka-ui-kafka-ui-1  | 	ssl.secure.random.implementation = null
kafka-ui-kafka-ui-1  | 	ssl.trustmanager.algorithm = PKIX
kafka-ui-kafka-ui-1  | 	ssl.truststore.certificates = null
kafka-ui-kafka-ui-1  | 	ssl.truststore.location = null
kafka-ui-kafka-ui-1  | 	ssl.truststore.password = null
kafka-ui-kafka-ui-1  | 	ssl.truststore.type = JKS
kafka-ui-kafka-ui-1  | 
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:37,342 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka version: 3.3.1
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:37,343 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka commitId: e23c59d00e687ff5
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:37,343 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1678381237341
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:37,691 ERROR [parallel-1] c.p.k.u.s.StatisticsService: Failed to collect cluster local info
kafka-ui-kafka-ui-1  | java.lang.IllegalStateException: Error while creating AdminClient for Cluster local
kafka-ui-kafka-ui-1  | 	at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3776)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
kafka-ui-kafka-ui-1  | 	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
kafka-ui-kafka-ui-1  | 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
kafka-ui-kafka-ui-1  | 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
kafka-ui-kafka-ui-1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka-ui-kafka-ui-1  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
kafka-ui-kafka-ui-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
kafka-ui-kafka-ui-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
kafka-ui-kafka-ui-1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
kafka-ui-kafka-ui-1  | Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default includeClusterAuthorizedOperations at version 5
kafka-ui-kafka-ui-1  | 2023-03-09 17:00:37,692 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: local

```

**Comment by iliax** [comment]
@robsonpeixoto Thank you for the issue. 

Can you please check this again on `latest` tag (it was released just 16 hours ago) or explicitly set tag to `v0.6.0` ? 
it should be fixed in this version

**Comment by robsonpeixoto** [comment]
Thanks @iliax =D It's working very well =D

**Comment by havilasaulo** [comment]
Como foi resolvido esse problema, está acontecendo o mesmo comigo

**Comment by germanosin** [comment]
@havilasaulo 
Me and @Haarolean no longer support this repo.
Don't you mind to propose your request to our repo https://github.com/kafbat/kafka-ui
