### ISSUE TITLE
schema registry ui 500 Internal Server Error

### ISSUE THREAD

**Issue by newsbreak-tonglin** [provectus/kafka-ui#3506]
2023-03-16 11:36:09 2023-03-16 03:36:09,258 ERROR [reactor-http-epoll-3] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [b4de322b-25]  500 Server Error for HTTP GET "/api/clusters/novastaging/schemas/compatibility"
2023-03-16 11:36:09 org.springframework.web.reactive.function.client.WebClientResponseException: 200 OK from GET http://schema-registry.k8s.xxxx.com/config/; nested exception is org.springframework.web.reactive.function.UnsupportedMediaTypeException: Content type 'text/html;charset=utf-8' not supported for bodyType=com.provectus.kafka.ui.sr.model.CompatibilityConfig
2023-03-16 11:36:09     at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:250)
2023-03-16 11:36:09     Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
2023-03-16 11:36:09 Error has been observed at the following site(s):
2023-03-16 11:36:09     *__checkpoint ⇢ Handler com.provectus.kafka.ui.controller.SchemasController#getGlobalSchemaCompatibilityLevel(String, ServerWebExchange) [DispatcherHandler]
2023-03-16 11:36:09     *__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ HTTP GET "/api/clusters/novastaging/schemas/compatibility" [ExceptionHandlingWebHandler]
2023-03-16 11:36:09 Original Stack Trace:
2023-03-16 11:36:09             at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:250)
2023-03-16 11:36:09             at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:207)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
2023-03-16 11:36:09             at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onError(FluxOnErrorReturn.java:199)
2023-03-16 11:36:09             at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1863)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)
2023-03-16 11:36:09             at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onError(FluxMapFuseable.java:340)
2023-03-16 11:36:09             at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onError(FluxFilterFuseable.java:382)
2023-03-16 11:36:09             at reactor.core.publisher.MonoCollect$CollectSubscriber.onError(MonoCollect.java:145)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
2023-03-16 11:36:09             at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
2023-03-16 11:36:09             at reactor.core.publisher.Operators.error(Operators.java:198)
2023-03-16 11:36:09             at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:182)
2023-03-16 11:36:09             at reactor.netty.channel.FluxReceive.subscribe(FluxReceive.java:143)
2023-03-16 11:36:09             at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
2023-03-16 11:36:09             at reactor.netty.ByteBufFlux.subscribe(ByteBufFlux.java:340)
2023-03-16 11:36:09             at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
2023-03-16 11:36:09             at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
2023-03-16 11:36:09             at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
2023-03-16 11:36:09             at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onError(FluxConcatArray.java:207)
2023-03-16 11:36:09             at reactor.core.publisher.Operators.error(Operators.java:198)
2023-03-16 11:36:09             at reactor.core.publisher.FluxError.subscribe(FluxError.java:43)
2023-03-16 11:36:09             at reactor.core.publisher.Flux.subscribe(Flux.java:8526)
2023-03-16 11:36:09             at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:258)
2023-03-16 11:36:09             at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
2023-03-16 11:36:09             at reactor.core.publisher.FluxTakeWhile$TakeWhileSubscriber.onComplete(FluxTakeWhile.java:122)
2023-03-16 11:36:09             at reactor.core.publisher.FluxTakeWhile$TakeWhileSubscriber.onNext(FluxTakeWhile.java:96)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
2023-03-16 11:36:09             at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
2023-03-16 11:36:09             at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:364)
2023-03-16 11:36:09             at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404)
2023-03-16 11:36:09             at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685)
2023-03-16 11:36:09             at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-03-16 11:36:09             at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-03-16 11:36:09             at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
2023-03-16 11:36:09             at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
2023-03-16 11:36:09             at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
2023-03-16 11:36:09             at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-03-16 11:36:09             at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-03-16 11:36:09             at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
2023-03-16 11:36:09             at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
2023-03-16 11:36:09             at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
2023-03-16 11:36:09             at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-03-16 11:36:09             at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-03-16 11:36:09             at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-03-16 11:36:09             at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-16 11:36:09 Caused by: org.springframework.web.reactive.function.UnsupportedMediaTypeException: Content type 'text/html;charset=utf-8' not supported for bodyType=com.provectus.kafka.ui.sr.model.CompatibilityConfig
2023-03-16 11:36:09     at org.springframework.web.reactive.function.BodyExtractors.lambda$readWithMessageReaders$12(BodyExtractors.java:201)
2023-03-16 11:36:09     Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
2023-03-16 11:36:09 Error has been observed at the following site(s):
2023-03-16 11:36:09     *__checkpoint ⇢ Body from GET http://schema-registry.k8s.xxxx.com/config/ [DefaultClientResponse]
2023-03-16 11:36:09 Original Stack Trace:
2023-03-16 11:36:09             at org.springframework.web.reactive.function.BodyExtractors.lambda$readWithMessageReaders$12(BodyExtractors.java:201)
2023-03-16 11:36:09             at java.base/java.util.Optional.orElseGet(Optional.java:364)
2023-03-16 11:36:09             at org.springframework.web.reactive.function.BodyExtractors.readWithMessageReaders(BodyExtractors.java:197)
2023-03-16 11:36:09             at org.springframework.web.reactive.function.BodyExtractors.lambda$toMono$2(BodyExtractors.java:85)
2023-03-16 11:36:09             at org.springframework.web.reactive.function.client.DefaultClientResponse.body(DefaultClientResponse.java:131)
2023-03-16 11:36:09             at org.springframework.web.reactive.function.client.DefaultClientResponse.bodyToMono(DefaultClientResponse.java:151)
2023-03-16 11:36:09             at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.lambda$bodyToMono$3(DefaultWebClient.java:548)
2023-03-16 11:36:09             at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
2023-03-16 11:36:09             at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
2023-03-16 11:36:09             at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
2023-03-16 11:36:09             at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
2023-03-16 11:36:09             at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
2023-03-16 11:36:09             at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
2023-03-16 11:36:09             at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
2023-03-16 11:36:09             at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
2023-03-16 11:36:09             at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:150)
2023-03-16 11:36:09             at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:189)
2023-03-16 11:36:09             at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
2023-03-16 11:36:09             at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
2023-03-16 11:36:09             at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:172)
2023-03-16 11:36:09             at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:431)
2023-03-16 11:36:09             at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677)
2023-03-16 11:36:09             at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:187)
2023-03-16 11:36:09             at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:444)
2023-03-16 11:36:09             at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:637)
2023-03-16 11:36:09             at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-03-16 11:36:09             at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-03-16 11:36:09             at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
2023-03-16 11:36:09             at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
2023-03-16 11:36:09             at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
2023-03-16 11:36:09             at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
2023-03-16 11:36:09             at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
2023-03-16 11:36:09             at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-03-16 11:36:09             at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-03-16 11:36:09             at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
2023-03-16 11:36:09             at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
2023-03-16 11:36:09             at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
2023-03-16 11:36:09             at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-03-16 11:36:09             at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-03-16 11:36:09             at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-03-16 11:36:09             at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-16 11:36:09 2023-03-16 03:36:09,260 ERROR [reactor-http-epoll-4] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [0f65b4ee-26]  500 Server Error for HTTP GET "/api/clusters/novastaging/schemas?page=1&perPage=25"
2023-03-16 11:36:09 com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
2023-03-16 11:36:09  at [Source: (String)"<html><head><title>Loading...</title></head><body><script type='text/javascript'>window.location.replace('http://schema-registry.k8s.xxxx.com/subjects?ch=1&deleted=false&js=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTY3ODk0NDk2OSwiaWF0IjoxNjc4OTM3NzY5LCJpd3MiOiJKb2tlbiIsImpaIjoxLCJqdGkiOiIydDZjaTBidTIwZGRmb2p2cmMyajExazIiLCJuYmYiOjE2Nzg5Mzc3NjksInRzIjoxNjc4OTM3NzY5MzQ5NDQyfQ.APw9EPLh0NEsjqBfGxqkELry7i-exIcLlHdEKQgqOjk&sid=b0ec3722-c3ab-11ed-917a-308b685d79b7');</script>"[truncated 14 chars]; line: 1, column: 2]
2023-03-16 11:36:09     at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
2023-03-16 11:36:09     Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
2023-03-16 11:36:09 Error has been observed at the following site(s):
2023-03-16 11:36:09     *__checkpoint ⇢ Handler com.provectus.kafka.ui.controller.SchemasController#getSchemas(String, Integer, Integer, String, ServerWebExchange) [DispatcherHandler]
2023-03-16 11:36:09     *__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
2023-03-16 11:36:09     *__checkpoint ⇢ HTTP GET "/api/clusters/novastaging/schemas?page=1&perPage=25" [ExceptionHandlingWebHandler]
2023-03-16 11:36:09 Original Stack Trace:
2023-03-16 11:36:09             at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
2023-03-16 11:36:09             at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
2023-03-16 11:36:09             at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
2023-03-16 11:36:09             at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
2023-03-16 11:36:09             at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
2023-03-16 11:36:09             at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
2023-03-16 11:36:09             at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
2023-03-16 11:36:09             at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
2023-03-16 11:36:09             at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3612)
2023-03-16 11:36:09             at com.provectus.kafka.ui.service.SchemaRegistryService.parseSubjectListString(SchemaRegistryService.java:68)
2023-03-16 11:36:09             at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:351)
2023-03-16 11:36:09             at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:686)
2023-03-16 11:36:09             at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:250)
2023-03-16 11:36:09             at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
2023-03-16 11:36:09             at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
2023-03-16 11:36:09             at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
2023-03-16 11:36:09             at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
2023-03-16 11:36:09             at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
2023-03-16 11:36:09             at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
2023-03-16 11:36:09             at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
2023-03-16 11:36:09             at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2023-03-16 11:36:09             at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
2023-03-16 11:36:09             at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2023-03-16 11:36:09             at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
2023-03-16 11:36:09             at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
2023-03-16 11:36:09             at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
2023-03-16 11:36:09             at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:702)
2023-03-16 11:36:09             at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-03-16 11:36:09             at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-03-16 11:36:09             at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
2023-03-16 11:36:09             at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
2023-03-16 11:36:09             at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
2023-03-16 11:36:09             at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-03-16 11:36:09             at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2023-03-16 11:36:09             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-03-16 11:36:09             at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-03-16 11:36:09             at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
2023-03-16 11:36:09             at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
2023-03-16 11:36:09             at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
2023-03-16 11:36:09             at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-03-16 11:36:09             at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-03-16 11:36:09             at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-03-16 11:36:09             at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-16 11:36:09 2023-03-16 03:36:09,262 DEBUG [reactor-http-epoll-3] o.s.h.c.j.Jackson2JsonEncoder: [b4de322b-25] Encoding [class ErrorResponseDTO {<EOL>    code: 5000<EOL>    message: 200 OK from GET http://schema-registry.k8s.xxx (truncated)...]
2023-03-16 11:36:09 2023-03-16 03:36:09,263 DEBUG [reactor-http-epoll-4] o.s.h.c.j.Jackson2JsonEncoder: [0f65b4ee-26] Encoding [class ErrorResponseDTO {<EOL>    code: 5000<EOL>    message: Unexpected character ('<' (code 60)): expected  (truncated)...]

![image](https://user-images.githubusercontent.com/90182037/225251951-12a95d18-a5d1-4767-a02a-cd72d14581a2.png)

**Comment by Haarolean** [comment]
The response we encountered from your SR wasn't a valid JSON, it's mixed with some HTML.

```
<title>Loading...</title><script type='text/javascript'>window.location.replace('http://schema-registry.k8s.xxxx.com/subjects?ch=1&deleted=false&js=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTY3ODk0NDk2OSwiaWF0IjoxNjc4OTM3NzY5LCJpd3MiOiJKb2tlbiIsImpaIjoxLCJqdGkiOiIydDZjaTBidTIwZGRmb2p2cmMyajExazIiLCJuYmYiOjE2Nzg5Mzc3NjksInRzIjoxNjc4OTM3NzY5MzQ5NDQyfQ.APw9EPLh0NEsjqBfGxqkELry7i-exIcLlHdEKQgqOjk&sid=b0ec3722-c3ab-11ed-917a-308b685d79b7');</script>"[truncated 14 chars]; line: 1, column: 2]
```

**Comment by newsbreak-tonglin** [comment]
@Haarolean Thank for your reply. I hava resolved this problem. It caused by incorrect k8s dns settings.
