### ISSUE TITLE
`IllegalArgumentException: Actual request host must not be null` for some asserts. When using behind nginx

### ISSUE THREAD

**Issue by gam6itko** [provectus/kafka-ui#3854]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I'm using docker container behind proxy (nginx).

When I try to load the index page I get a blank page. In DevTools I see that It can't load 2 (http status: 500) files: `/assets/index-72a1fb9c.js`, `/assets/ace-042f3d64.js`.
If I try to download them directly (https://kafka-ui.mydomain.dev/assets/index-72a1fb9c.js, https://kafka-ui.mydomain.dev/assets//assets/ace-042f3d64.js), then there is no such problem (http status: 200).

### Your installation details

1. I don't see Current commit. I use [this docker image](https://hub.docker.com/layers/provectuslabs/kafka-ui/master/images/sha256-16a3acb838398bad7597afdbf65fddc4dec415f9f077b028db41b0137af610c9?context=explore).
2. No Helm.

kafka-ui docker env
```
"SERVER_PORT=8092",
"KAFKA_CLUSTERS_0_NAME=devserver",
"KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.10.10:9092",
"KAFKA_CLUSTERS_0_METRICS_PORT=9997",
```

### Steps to reproduce

nginx config
```
upstream kafka_ui {
    server 192.168.10.10:8092;
}

server {
    listen 443 ssl http2;
    server_name kafka-ui.mydomain.dev;

    location / {
        proxy_pass http://kafka_ui;
    }

    ssl_certificate /etc/ssl/mydomain.dev.chained.crt;
    ssl_certificate_key /etc/ssl/mydomain.dev.key;
}
```

### Logs

Docker container errors.
```
ERROR [parallel-32] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [4fb0dca3-17]  500 Server Error for HTTP GET "/assets/index-72a1fb9c.js"
java.lang.IllegalArgumentException: Actual request host must not be null
	at org.springframework.util.Assert.notNull(Assert.java:204)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/assets/index-72a1fb9c.js" [ExceptionHandlingWebHandler]


ERROR [parallel-1] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [286fec7f-16]  500 Server Error for HTTP GET "/assets/ace-042f3d64.js"
java.lang.IllegalArgumentException: Actual request host must not be null
	at org.springframework.util.Assert.notNull(Assert.java:204)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/assets/ace-042f3d64.js" [ExceptionHandlingWebHandler]

```

nginx access.log
```
"GET / HTTP/2.0" 200 1003 len:18 elapsed:0.009
"GET /assets/index-d9d582cd.css HTTP/2.0" 200 1893 len:34 elapsed:0.012
"GET /assets/index-72a1fb9c.js HTTP/2.0" 500 13453 len:35 elapsed:0.016
"GET /assets/ace-042f3d64.js HTTP/2.0" 500 13451 len:33 elapsed:0.016
"GET /manifest.json HTTP/2.0" 200 566 len:26 elapsed:0.009
"GET /favicon/icon.svg HTTP/2.0" 200 1043 len:28 elapsed:0.010
"GET /favicon/favicon.ico HTTP/2.0" 200 4640 len:30 elapsed:0.010
```

**Comment by Haarolean** [comment]
Hi, that's an issue for your infra, most likely the nignx config.
We have a docker-compose example with nginx as a reverse proxy [here](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-reverse-proxy.yaml) and it works perfectly fine with [this](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/proxy.conf) nginx config

**Comment by gam6itko** [comment]
It's weird but it started working after I replace `_` to `-` in the upstream name.
Upstream name changed from  `kafka_ui` to `kafka-ui`.
