### ISSUE TITLE
Connection issue/Error when adding Kafka Connect

### ISSUE THREAD

**Issue by Vijay-Nirmal** [provectus/kafka-ui#4013]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Connection issue when adding Kafka Connect. Without adding Kafka connect url, it is connecting/working properly.

**Error message:**
![image](https://github.com/provectus/kafka-ui/assets/24755596/d6c63cd7-5be2-4d9d-a410-11afb4c88f39)

**Config:**
![image](https://github.com/provectus/kafka-ui/assets/24755596/667f5129-9115-4764-8ffa-209fb8ca5599)

_**Note:** Kafka Connect is hosted in the same cluster under same namespace_

### Your installation details

1. App version: latest (v0.7.1 [56fa824](https://github.com/provectus/kafka-ui/commit/56fa824))
2. Configuration :
```yml
auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: abcd.eastus.azure.confluent.cloud:9092
    kafkaConnect:
    - address: http://kafka-connect-cluster
      name: Dev
    name: Non Prod
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required
        username="abcd" password="wxyz";
    readOnly: false
rbac:
  roles: []
webclient: {}
```

_**Note:** Kafka Connect is hosted in the same cluster under same namespace_

### Steps to reproduce

1. Added Kafka Connect details in yaml or in dynamic config page
2. Navigate to Kafka Connect page

### Logs

```
ERROR [reactor-http-epoll-7] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [9689fc97-836]  500 Server Error for HTTP GET "/api/clusters/Non%20Prod/connectors"
2023-07-05T12:40:58.960339189Z org.springframework.web.reactive.function.client.WebClientRequestException: null: kafka-connect-cluster.qs-flex-dev.svc.cluster.local/172.20.215.94:80
2023-07-05T12:40:58.960345189Z 	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
2023-07-05T12:40:58.960351590Z 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
2023-07-05T12:40:58.960358091Z Error has been observed at the following site(s):
2023-07-05T12:40:58.960364991Z 	*__checkpoint ⇢ Request to GET http://kafka-connect-cluster/connectors [DefaultWebClient]
2023-07-05T12:40:58.960372092Z 	*__checkpoint ⇢ Handler com.provectus.kafka.ui.controller.KafkaConnectController#getAllConnectors(String, String, ConnectorColumnsToSortDTO, SortOrderDTO, ServerWebExchange) [DispatcherHandler]
2023-07-05T12:40:58.960378893Z 	*__checkpoint ⇢ com.provectus.kafka.ui.config.CorsGlobalConfiguration$$Lambda$984/0x000000080162baf0 [DefaultWebFilterChain]
	*__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960391594Z 	*__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960396094Z 	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960400095Z 	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960406195Z 	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960412396Z 	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960417996Z 	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960423997Z 	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960430198Z 	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960435498Z 	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960441599Z 	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
2023-07-05T12:40:58.960453500Z 	*__checkpoint ⇢ HTTP GET "/api/clusters/Non%20Prod/connectors" [ExceptionHandlingWebHandler]
2023-07-05T12:40:58.960460101Z Original Stack Trace:
2023-07-05T12:40:58.960465601Z 		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
2023-07-05T12:40:58.960470802Z 		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
2023-07-05T12:40:58.960476002Z 		at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
2023-07-05T12:40:58.960481003Z 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
2023-07-05T12:40:58.960487003Z 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2023-07-05T12:40:58.960492804Z 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2023-07-05T12:40:58.960497904Z 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2023-07-05T12:40:58.960504305Z 		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
2023-07-05T12:40:58.960525307Z 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
2023-07-05T12:40:58.960530907Z 		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
2023-07-05T12:40:58.960535908Z 		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
2023-07-05T12:40:58.960541108Z 		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
2023-07-05T12:40:58.960547009Z 		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
2023-07-05T12:40:58.960553210Z 		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.maybeOnError(FluxCo
ncatMapNoPrefetch.java:326)
2023-07-05T12:40:58.960559110Z 		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:211)
2023-07-05T12:40:58.960564611Z 		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2023-07-05T12:40:58.960569911Z 		at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:471)
2023-07-05T12:40:58.960575212Z 		at reactor.core.publisher.SinkManyEmitterProcessor$EmitterInner.drainParent(SinkManyEmitterProcessor.java:615)
2023-07-05T12:40:58.960596314Z 		at reactor.core.publisher.FluxPublish$PubSubInner.request(FluxPublish.java:602)
2023-07-05T12:40:58.960618616Z 		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
2023-07-05T12:40:58.960623916Z 		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:336)
2023-07-05T12:40:58.960627717Z 		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
2023-07-05T12:40:58.960632617Z 		at reactor.core.publisher.Operators$DeferredSubscription.request(Operators.java:1717)
2023-07-05T12:40:58.960638118Z 		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:192)
2023-07-05T12:40:58.960643518Z 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
2023-07-05T12:40:58.960649219Z 		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:311)
2023-07-05T12:40:58.960655320Z 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
2023-07-05T12:40:58.960667021Z 		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:162)
2023-07-05T12:40:58.960671821Z 		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475)

2023-07-05T12:40:58.960677822Z 		at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:429)
2023-07-05T12:40:58.960683422Z 		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
2023-07-05T12:40:58.960689023Z 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:560)
2023-07-05T12:40:58.960701324Z 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241)
2023-07-05T12:40:58.960706825Z 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315)
2023-07-05T12:40:58.960712625Z 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
2023-07-05T12:40:58.960718626Z 		at reactor.core.publisher.Operators.error(Operators.java:198)
2023-07-05T12:40:58.960733027Z 		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
2023-07-05T12:40:58.960738928Z 		at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
2023-07-05T12:40:58.960751029Z 		at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:587)
2023-07-05T12:40:58.960756529Z 		at reactor.netty.transport.TransportConnector$MonoChannelPromise.setFailure(TransportConnector.java:541)
2023-07-05T12:40:58.960763430Z 		at reactor.netty.transport.TransportConnector.lambda$doConnect$7(TransportConnector.java:265)
2023-07-05T12:40:58.960768131Z 		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
2023-07-05T12:40:58.960771931Z 		at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
2023-07-05T12:40:58.960776531Z 		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
2023-07-05T12:40:58.960780432Z 		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
2023-07-05T12:40:58.960784232Z 		at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
2023-07-05T12:40:58.960787932Z 		at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
2023-07-05T12:40:58.960791733Z 		at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
2023-07-05T12:40:58.960795633Z 		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:674)
2023-07-05T12:40:58.960799834Z 		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:693)
2023-07-05T12:40:58.960805034Z 		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
2023-07-05T12:40:58.960810335Z 		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
2023-07-05T12:40:58.960819135Z 		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-07-05T12:40:58.960831437Z 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-07-05T12:40:58.960838637Z 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
2023-07-05T12:40:58.960850539Z Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: null: kafka-connect-cluster.qs-flex-dev.svc.cluster.local/172.20.215.94:80
2023-07-05T12:40:58.960856839Z Caused by: java.net.NoRouteToHostException: null
2023-07-05T12:40:58.960862240Z 	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:158)
2023-07-05T12:40:58.960890742Z 	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
2023-07-05T12:40:58.960909544Z 	at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
2023-07-05T12:40:58.960915945Z 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
2023-07-05T12:40:58.960921445Z 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
2023-07-05T12:40:58.960926346Z 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
2023-07-05T12:40:58.960931846Z 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
2023-07-05T12:40:58.960937447Z 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
2023-07-05T12:40:58.960952348Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-07-05T12:40:58.960958149Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-07-05T12:40:58.960964250Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-07-05T12:40:58.960970150Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Haarolean** [comment]
Hi, logs say that there's no route to KC host. Please try pinging `kafka-connect-cluster.qs-flex-dev.svc.cluster.local` from inside kkafka-ui's container.

**Comment by Vijay-Nirmal** [comment]
@Haarolean Thanks, Found the issue because of your hint. Kafka connector was not running in port 80, it was running in different port but I didn't configure the port in the url. Thanks
