### ISSUE TITLE
Okta authentication does not respect proxy settings

### ISSUE THREAD

**Issue by poom-kitti** [provectus/kafka-ui#4114]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

To give some context, our Kafka UI is deployed in a server inside a virtual private network. This mean:
- The client (user connecting to Kafka UI) is also in the private network but is capable of accessing the internet
- The Kafka UI is unable to access the internet unless using a proxy server

When Kafka UI is deployed in the server, it does not respect using proxy declared in any of the following Java system properties when performing connection to Okta to perform authentication:
- http.proxyHost
- http.proxyPort
- http.nonProxyHosts
- https.proxyHost
- https.proxyPort
- https.nonProxyHosts

Once a client tried to connect to Kafka UI, they are directed to authenticate to Okta correctly. However, after the client passed the code which they received from Okta back to Kafka UI triggering Kafka UI to perform POST request to Okta's token URI, it fails due to `java.net.NoRouteToHostException` indicating that the proxy is not in-use.

From some exploration, I believe that Spring security is using the `DefaultWebClient` to perform authentication and this WebClient does not respect the system properties on using proxy.

### Expected behavior

When specified the system property like `-Dhttps.proxyHost=my.proxy.host -Dhttps.proxyPort=3218 -Dhttps.nonProxyHosts=XXXX.local|10.*`, the authentication should be using proxy to make connection to Okta.

### Your installation details

App version: 0.7.1 (as of commit [`b32ab0143679bd3224f097a9de0eefad4e60f8d6`](https://github.com/provectus/kafka-ui/commit/b32ab0143679bd3224f097a9de0eefad4e60f8d6))

Application YAML:
I deliberately did not add any configuration regarding connection to Kafka as it is unnecessary to show behavior of Okta authentication. In addition, this way, it make showing debug log clearer as we will only get debug log regarding authentication.

```
auth:
  type: OAUTH2
  oauth2:
    client:
      okta:
        clientId: <client-id>
        clientSecret: <client-secret>
        scope: [ 'openid', 'profile', 'email', 'groups' ]
        client-name: Okta
        provider: okta
        redirect-uri: "{baseUrl}/login/oauth2/code/okta"
        authorization-grant-type: authorization_code
        issuer-uri: https://<okta-endpoint>
        authorization-uri: https://<okta-endpoint>/oauth2/v1/authorize
        token-uri: https://<okta-endpoint>/oauth2/v1/token
        user-info-uri: https://<okta-endpoint>/oauth2/v1/userinfo
        jwk-set-uri: https://<okta-endpoint>/oauth2/v1/keys
        user-name-attribute: email
        custom-params:
          type: oauth
          roles-field: groups
server:
  port: 8080
```

### Steps to reproduce

1. Add authentication with Okta configurations.
2. Build the Docker image.
3. Create a Docker container inside a server that cannot access the internet except through proxy server.
4. Start Kafka UI with Java system properties related to proxy:
- http.proxyHost
- http.proxyPort
- http.nonProxyHosts
- https.proxyHost
- https.proxyPort
- https.nonProxyHosts
5. Try to access Kafka UI and perform Okta authentication.

### Screenshots

From the network tab in developer tool, we can see that Okta returns some code to user and this is passed to Kafka UI; however the get request to `<kafka ui endpoint>/login/oauth2/code/okta?code=<some code>` failed.

![error_pixelate](https://github.com/provectus/kafka-ui/assets/46432146/fb7d1924-d10b-4d49-8cef-2789f48a3587)

### Logs

From logs, I see the following error:
```
[30m2023-08-12 22:48:08,259[0;39m [1;31mERROR[0;39m [[34mreactor-http-epoll-3[0;39m] [33mo.s.b.a.w.r.e.AbstractErrorWebExceptionHandler[0;39m: [8200782c-3]  500 Server Error for HTTP GET "/login/oauth2/code/okta?code=pV9h3TwnnHan7NjkEYWZR6oPKMcBU8WTrH3m4tLMX40&state=VHDFtviuySJvVcmLMwurglU1u81s1mw1Bw32_BlUD4Y%3D"
org.springframework.web.reactive.function.client.WebClientRequestException: null: dev-61615254.okta.com/99.83.233.105:443
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to POST https://dev-61615254.okta.com/oauth2/v1/token [DefaultWebClient]
	*__checkpoint ⇢ OAuth2LoginAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OAuth2AuthorizationRequestRedirectWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/login/oauth2/code/okta?code=pV9h3TwnnHan7NjkEYWZR6oPKMcBU8WTrH3m4tLMX40&state=VHDFtviuySJvVcmLMwurglU1u81s1mw1Bw32_BlUD4Y%3D" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.maybeOnError(FluxConcatMapNoPrefetch.java:326)
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:211)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:471)
		at reactor.core.publisher.SinkManyEmitterProcessor$EmitterInner.drainParent(SinkManyEmitterProcessor.java:615)
		at reactor.core.publisher.FluxPublish$PubSubInner.request(FluxPublish.java:602)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:336)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
		at reactor.core.publisher.Operators$DeferredSubscription.request(Operators.java:1717)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:192)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:311)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:162)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475)
		at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:429)
		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:560)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.maybeOnError(FluxConcatMapNoPrefetch.java:326)
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:211)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:471)
		at reactor.core.publisher.SinkManyEmitterProcessor$EmitterInner.drainParent(SinkManyEmitterProcessor.java:615)
		at reactor.core.publisher.FluxPublish$PubSubInner.request(FluxPublish.java:602)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:336)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
		at reactor.core.publisher.Operators$DeferredSubscription.request(Operators.java:1717)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:192)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315)
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:587)
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.setFailure(TransportConnector.java:541)
		at reactor.netty.transport.TransportConnector.lambda$doConnect$7(TransportConnector.java:265)
		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
		at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
		at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
		at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
		at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:674)
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:693)
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: null: dev-61615254.okta.com/99.83.233.105:443
Caused by: java.net.NoRouteToHostException: null
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:158)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

When setting the environment variable `LOGGING_LEVEL_ROOT=debug` to show debug log, I see the following logs that signify that Kafka UI is trying to connect to the Okta endpoint directly. This should not be the case because it should use proxy instead.
```
[30m2023-08-12 22:51:21,497[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mo.s.w.r.f.c.ExchangeFunctions[0;39m: [62de54f3] HTTP POST https://dev-61615254.okta.com/oauth2/v1/token
[30m2023-08-12 22:51:21,684[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mi.n.r.d.DnsNameResolver[0;39m: [id: 0xfd2c1ad8] RECEIVED: UDP [43221: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, id: 43221, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(dev-61615254.okta.com. IN A)
	DefaultDnsRawRecord(dev-61615254.okta.com. 270 IN CNAME 25B)
	DefaultDnsRawRecord(ok12-crtrs.tng.okta.com. 30 IN CNAME 30B)
	DefaultDnsRawRecord(ok12-crtrs.oktaedge.okta.com. 270 IN CNAME 44B)
	DefaultDnsRawRecord(a1c0075a909445e0e.awsglobalaccelerator.com. 75 IN A 4B)
	DefaultDnsRawRecord(a1c0075a909445e0e.awsglobalaccelerator.com. 75 IN A 4B)
	DefaultDnsRawRecord(OPT flags:0 udp:4000 0B)
[30m2023-08-12 22:51:21,688[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mr.n.t.TransportConnector[0;39m: [5de47a0b] Connecting to [dev-61615254.okta.com/75.2.37.199:443].
[30m2023-08-12 22:51:21,690[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mr.n.t.TransportConnector[0;39m: [5de47a0b] Connect attempt to [dev-61615254.okta.com/75.2.37.199:443] failed.       
```

**Comment by poom-kitti** [comment]
I did get the proxy to work by implementing `OidcAuthorizationCodeReactiveAuthenticationManager` (OAuth2 equivalent is `OAuth2LoginReactiveAuthenticationManager`) and set to use this manager for login. 

The manager seems to interact with Okta for 3 things and the following classes are used for those interactions:
- Exchange of token via `token-uri` by `WebClientReactiveAuthorizationCodeTokenResponseClient`
- Exchange of JWT via `jwk-set-uri` by `NimbusReactiveJwtDecoder`
- Exchange of user information via `authorization-uri` by `OidcReactiveOAuth2UserService` (OAuth2 equivalent is `DefaultReactiveOAuth2UserService`)
Therefore, we will need to somehow set WebClient that respect proxy settings for these 3 exchanges.

## My Solution
I get the proxy system properties to work by making following changes in `OAuthSecurityConfig`:
```
@Configuration
@ConditionalOnProperty(value = "auth.type", havingValue = "OAUTH2")
@EnableConfigurationProperties(OAuthProperties.class)
@EnableWebFluxSecurity
@EnableReactiveMethodSecurity
@RequiredArgsConstructor
@Log4j2
public class OAuthSecurityConfig extends AbstractAuthSecurityConfig {

  private final OAuthProperties properties;

  // 1. Create WebClient that respects proxy settings
  private WebClient webClient = new WebClientConfigurator().build();

  @Bean
  public SecurityWebFilterChain configure(
      ServerHttpSecurity http,
      OAuthLogoutSuccessHandler logoutHandler,
      CustomOidcAuthenticationManagerBuilder oidcAuthenticationManagerBuilder
  ) {
    log.info("Configuring OAUTH2 authentication.");

    return http.authorizeExchange(spec -> spec
            .pathMatchers(AUTH_WHITELIST)
            .permitAll()
            .anyExchange()
            .authenticated()
        )
        .oauth2Login(spec -> spec.authenticationManager(oidcAuthenticationManagerBuilder.build())) // 2. Use custom authentication manager
        .logout(spec -> spec.logoutSuccessHandler(logoutHandler))
        .csrf(ServerHttpSecurity.CsrfSpec::disable)
        .build();
  }

  @Bean
  public ReactiveOAuth2UserService<OidcUserRequest, OidcUser> customOidcUserService(AccessControlService acs) {
    // 3. Use WebClient that respects proxy settings to get user-info
    final OidcReactiveOAuth2UserService delegate = new OidcReactiveOAuth2UserService();
    delegate.setOauth2UserService(customOauth2UserService(acs));
    ...
  }

  @Bean
  public ReactiveOAuth2UserService<OAuth2UserRequest, OAuth2User> customOauth2UserService(AccessControlService acs) {
    // 3. Use WebClient that respects proxy settings to get user-info
    final DefaultReactiveOAuth2UserService delegate = new DefaultReactiveOAuth2UserService();
    delegate.setWebClient(webClient);
    ...
  }
```

This is the code for `CustomOidcAuthenticationManagerBuilder` that I created (in a new file):
```
@Component
@ConditionalOnProperty(value = "auth.type", havingValue = "OAUTH2")
public class CustomOidcAuthenticationManagerBuilder {
  private WebClient webClient = new WebClientConfigurator().build();
  // Reuse customOidcUserService bean from `OAuthSecurityConfig`
  private ReactiveOAuth2UserService<OidcUserRequest, OidcUser> oidcUserService;
  @Value("${auth.oauth2.client.okta.jwk-set-uri}")
  private String jwkUri;

  public CustomOidcAuthenticationManagerBuilder(ReactiveOAuth2UserService<OidcUserRequest, OidcUser> oidcUserService) {
    this.oidcUserService = oidcUserService;
  }

  public OidcAuthorizationCodeReactiveAuthenticationManager build() {
    // Use WebClient that respects proxy settings to get token
    WebClientReactiveAuthorizationCodeTokenResponseClient client =
        new WebClientReactiveAuthorizationCodeTokenResponseClient();
    client.setWebClient(webClient);

    // Use WebClient that respects proxy settings to get JWT
    ReactiveJwtDecoderFactory<ClientRegistration> idTokenDecoderFactory =
        (clientRegistration) -> NimbusReactiveJwtDecoder.withJwkSetUri(jwkUri)
            .webClient(webClient)
            .build();

    OidcAuthorizationCodeReactiveAuthenticationManager manager =
        new OidcAuthorizationCodeReactiveAuthenticationManager(client, oidcUserService);
    manager.setJwtDecoderFactory(idTokenDecoderFactory);

    return manager;
  }
}
```

Please check my commit which should make this clearer: https://github.com/poom-kitti/kafka-ui/commit/3b88135168d99618bfa40da37885b996bb6d96a8

## Result
After applying the changes and rebuild Kafka UI along with deploying (using same Java system properties related to proxy), the authentication now works. I can confirm that proxy is used because from debug logs, instead of making connection to Okta directly, it is connecting to proxy instead.
```
[30m2023-08-12 23:15:49,863[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-4[0;39m] [33mo.s.w.r.f.c.ExchangeFunctions[0;39m: [52dec0ff] HTTP POST https://dev-61615254.okta.com/oauth2/v1/token
[30m2023-08-12 23:15:49,865[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mr.n.r.PooledConnectionProvider[0;39m: [d894b024, L:/172.19.0.4:36860 - R:my.proxy.host/10.118.87.223:3128] Channel acquired, now: 1 active connections, 1 inactive connections and 0 pending acquire requests.
[30m2023-08-12 23:15:49,865[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mr.n.h.c.HttpClientConnect[0;39m: [d894b024-2, L:/172.19.0.4:36860 - R:my.proxy.host/10.118.87.223:3128] Handler is being applied: {uri=https://dev-61615254.okta.com/oauth2/v1/token, method=POST}
[30m2023-08-12 23:15:49,865[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mr.n.r.DefaultPooledConnectionProvider[0;39m: [d894b024-2, L:/172.19.0.4:36860 - R:my.proxy.host/10.118.87.223:3128] onStateChange(POST{uri=/oauth2/v1/token, connection=PooledConnection{channel=[id: 0xd894b024, L:/172.19.0.4:36860 - R:my.proxy.host/10.118.87.223:3128]}}, [request_prepared])
[30m2023-08-12 23:15:49,866[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mo.s.h.c.FormHttpMessageWriter[0;39m: [52dec0ff] Writing form fields [grant_type, code, redirect_uri] (content masked)
[30m2023-08-12 23:15:49,867[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mr.n.r.DefaultPooledConnectionProvider[0;39m: [d894b024-2, L:/172.19.0.4:36860 - R:my.proxy.host/10.118.87.223:3128] onStateChange(POST{uri=/oauth2/v1/token, connection=PooledConnection{channel=[id: 0xd894b024, L:/172.19.0.4:36860 - R:my.proxy.host/10.118.87.223:3128]}}, [request_sent])
[30m2023-08-12 23:15:50,128[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-3[0;39m] [33mr.n.h.c.HttpClientOperations[0;39m: [d894b024-2, L:/172.19.0.4:36860 - R:my.proxy.host/10.118.87.223:3128] Received response (auto-read:false) : RESPONSE(decodeResult: success, version: HTTP/1.1)
```

## Caveats
The drawback of my current implementations are:
1. It should only work with Oauth2 authentication that uses Open ID Connect protocol (not certain is this working for all Oauth2 authentication)
2. For `NimbusReactiveJwtDecoder`, it is using a static `jwk-set-uri` to point to Okta configuration which would not be generic if the provider is not Okta

Since I lack experience with Spring, I do not wish to claim this issue, but hope my investigation help in some way.

**Comment by Haarolean** [comment]
@poom-kitti Hi and thank you very much for the analysis, saved me some time in research.

Even if we implement the changes in other places, we won't be able to decode JWT token without these changes.
In the case of Okta / OIDC, we'd use the underlying `OidcAuthorizationCodeReactiveAuthenticationManager`, which, in turn,  does use `ReactiveOidcIdTokenDecoderFactory`, which doesn't allow customizing the webclient used for `NimbusReactiveJwtDecoder`. This behavior should be fixed within this spring-security issue: https://github.com/spring-projects/spring-security/issues/13274. There's already a PR but getting one merged and released would take some time.

Related: https://github.com/spring-projects/spring-security/issues/8882
Until that one is done, we'd have to customize the webclient manually for the following beans:
- `WebClientReactiveAuthorizationCodeTokenResponseClient`
- `WebClientReactiveRefreshTokenTokenResponseClient`
- `WebClientReactiveClientCredentialsTokenResponseClient`
- `WebClientReactivePasswordTokenResponseClient`
- `DefaultReactiveOAuth2UserService`

and probably some others which we need to determine on a per-use-case basis.

I suggest we put this on hold for some time to see if https://github.com/spring-projects/spring-security/issues/13274 does get any traction to see if we can avoid copy-pasting the whole factory bean.

**Comment by 1300371** [comment]
Some news about this fix ?

**Comment by Haarolean** [comment]
@1300371 this repo is not maintained: [source](https://github.com/provectus/kafka-ui/discussions/4255).
Please take a look at the mentioned issue right above your comment as well.

**Comment by seb2020** [comment]
Some news about this fix ?

**Comment by Haarolean** [comment]
@seb2020 see the comment above yours
