### ISSUE TITLE
Docker Build Crash: Caused by: java.io.IOException: Is a directory

### ISSUE THREAD

**Issue by MrChadMWood** [provectus/kafka-ui#4158]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The build fails with docker.

### Expected behavior

The build to work.

### Your installation details

No configuration. I just copied the code and ran it with Docker Desktop.

### Steps to reproduce

docker-compose up -d --build

```
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
      - ```

### Screenshots

![image](https://github.com/provectus/kafka-ui/assets/90083658/3711a2a8-ba3b-4a03-9240-d1d086e5a408)


### Logs

2023-08-24 11:21:08  _   _ ___    __             _                _          _  __      __ _
2023-08-24 11:21:08 | | | |_ _|  / _|___ _ _    /_\  _ __ __ _ __| |_  ___  | |/ /__ _ / _| |_____
2023-08-24 11:21:08 | |_| || |  |  _/ _ | '_|  / _ \| '_ / _` / _| ' \/ -_) | ' </ _` |  _| / / _`|
2023-08-24 11:21:08  \___/|___| |_| \___|_|   /_/ \_| .__\__,_\__|_||_\___| |_|\_\__,_|_| |_\_\__,|
2023-08-24 11:21:08                                  |_|                                             
2023-08-24 11:21:08 
2023-08-24 11:21:08 2023-08-24 18:21:08,160 INFO  [background-preinit] o.h.v.i.u.Version: HV000001: Hibernate Validator 8.0.0.Final
2023-08-24 11:21:09 2023-08-24 18:21:09,628 ERROR [main] o.s.b.SpringApplication: Application run failed
2023-08-24 11:21:09 org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Is a directory
2023-08-24 11:21:09     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:214)
2023-08-24 11:21:09     at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:172)
2023-08-24 11:21:09     at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:167)
2023-08-24 11:21:09     at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:122)
2023-08-24 11:21:09     at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1204)
2023-08-24 11:21:09     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:320)
2023-08-24 11:21:09     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
2023-08-24 11:21:09     at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:212)
2023-08-24 11:21:09     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
2023-08-24 11:21:09     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152)
2023-08-24 11:21:09     at org.yaml.snakeyaml.composer.Composer.checkNode(Composer.java:109)
2023-08-24 11:21:09     at org.yaml.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:149)
2023-08-24 11:21:09     at org.yaml.snakeyaml.Yaml$1.hasNext(Yaml.java:510)
2023-08-24 11:21:09     at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:199)
2023-08-24 11:21:09     at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:166)
2023-08-24 11:21:09     at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:83)
2023-08-24 11:21:09     at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
2023-08-24 11:21:09     at com.provectus.kafka.ui.util.DynamicConfigOperations.loadDynamicPropertySource(DynamicConfigOperations.java:84)
2023-08-24 11:21:09     at com.provectus.kafka.ui.util.DynamicConfigOperations.lambda$dynamicConfigPropertiesInitializer$1(DynamicConfigOperations.java:57)
2023-08-24 11:21:09     at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:605)
2023-08-24 11:21:09     at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:385)
2023-08-24 11:21:09     at org.springframework.boot.SpringApplication.run(SpringApplication.java:309)
2023-08-24 11:21:09     at com.provectus.kafka.ui.KafkaUiApplication.startApplication(KafkaUiApplication.java:24)
2023-08-24 11:21:09     at com.provectus.kafka.ui.KafkaUiApplication.main(KafkaUiApplication.java:17)
2023-08-24 11:21:09     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-08-24 11:21:09     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-08-24 11:21:09     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-08-24 11:21:09     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-08-24 11:21:09     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2023-08-24 11:21:09     at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
2023-08-24 11:21:09     at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2023-08-24 11:21:09     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
2023-08-24 11:21:09     Suppressed: java.io.IOException: Is a directory
2023-08-24 11:21:09             at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2023-08-24 11:21:09             at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
2023-08-24 11:21:09             at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330)
2023-08-24 11:21:09             at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
2023-08-24 11:21:09             at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
2023-08-24 11:21:09             at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:232)
2023-08-24 11:21:09             at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
2023-08-24 11:21:09             at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
2023-08-24 11:21:09             at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
2023-08-24 11:21:09             at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
2023-08-24 11:21:09             at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:182)
2023-08-24 11:21:09             at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:85)
2023-08-24 11:21:09             at org.yaml.snakeyaml.reader.UnicodeReader.close(UnicodeReader.java:112)
2023-08-24 11:21:09             at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:198)
2023-08-24 11:21:09             ... 18 common frames omitted
2023-08-24 11:21:09 Caused by: java.io.IOException: Is a directory
2023-08-24 11:21:09     at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2023-08-24 11:21:09     at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
2023-08-24 11:21:09     at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330)
2023-08-24 11:21:09     at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
2023-08-24 11:21:09     at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
2023-08-24 11:21:09     at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:232)
2023-08-24 11:21:09     at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
2023-08-24 11:21:09     at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
2023-08-24 11:21:09     at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
2023-08-24 11:21:09     at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
2023-08-24 11:21:09     at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:182)
2023-08-24 11:21:09     at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:85)
2023-08-24 11:21:09     at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:117)
2023-08-24 11:21:09     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:179)
2023-08-24 11:21:09     ... 31 common frames omitted

### Additional context

_No response_

**Comment by p-eye** [comment]
hi, did you create ~/kui/config.yml file before ?
if you didn't, there may be a directory named with config.yml

> If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v creates the endpoint for you. It is always created as a directory.
https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior

therefore when you create config.yml file before docker-compose run, it will works.

**Comment by MrChadMWood** [comment]
Yes. My project structure was as follows:

/kafka/
..|..docker-compose.yml
..|../kui/
..|..|..config.yml

**Comment by p-eye** [comment]
in my case, it doesn't matter if the file is empty or not as long as the file exists

**Comment by MrChadMWood** [comment]
Perhaps there is some clue to be found in here:
![image](https://github.com/provectus/kafka-ui/assets/90083658/aaa1f89d-3ffa-4d36-b601-46a49394ab29)

**Comment by p-eye** [comment]
maybe your path is `Documents/..{sth}../kafka/kui/config.yml` or something like that (you can get it with Windows 'cd' command)
instead of `~/kui/config.yml`

**Comment by MrChadMWood** [comment]
Oof, you are right!! Thanks. 
Changing `~` to `.` allowed the path to be relative. User error, and its working now,

**Comment by Haarolean** [comment]
@p-eye thanks ❤️
