### ISSUE TITLE
Support prometheus as a metrics interface

### ISSUE THREAD

**Issue by siddarthsreeni** [provectus/kafka-ui#442]
This is more of a bug on the existing minimalistic dashboard. I am connected to AWS MSK and Currently I do not see any realtime production/consumption metrics under tab General. There is no error in the logs.

![image](https://user-images.githubusercontent.com/72102697/117765169-32d45680-b24b-11eb-95d4-8e17e7a7f904.png)

**Comment by germanosin** [comment]
Hi @siddarthsreeni, thank you for creating this issue. Could you please share your config? Please make sure to pass jmx address to collect metrics.

**Comment by siddarthsreeni** [comment]
@germanosin Thanks for the input, I am currently using Aws MSK & have enabled "Open Monitoring" Under which the port `11001 `can be used by the JMX port. I tried like you suggested. I am getting the following errors when I add -e `KAFKA_CLUSTERS_0_JMXPORT=11001 `

But I understand that this is  "Open Monitoring" JMX port provides metrics from JMX, but it is Prometheus protocol. (Came here searching for whether Prometheus fetching had been added yet.) I was getting the following error

```
ERROR com.provectus.kafka.ui.util.JmxClusterUtil - Cannot invalidate object in pool, service:jmx:rmi:///jndi/rmi://xxx.xxxx.xxxx.kafka.us-east-1.amazonaws.com:11001/jmxrmi
       java.net.SocketTimeoutException: Read timed out]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:370) ~[?:?]
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
        at com.provectus.kafka.ui.util.JmxPoolFactory.create(JmxPoolFactory.java:17) ~[classes!/:?]
        at com.provectus.kafka.ui.util.JmxPoolFactory.create(JmxPoolFactory.java:12) ~[classes!/:?]
        at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.ja

```

Please not, In my configuration I have 2 different kafka cluster specificied, out of which I'm only looking forward to monitoring one of them (which is in MSK)

**Comment by Haarolean** [comment]
@MaratGumarov please note that there's a branch [issues/442](https://github.com/provectus/kafka-ui/compare/issues/442)
