### ISSUE TITLE
merge volume in docker can't start app 

### ISSUE THREAD

**Issue by shipcake** [provectus/kafka-ui#4504]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

**Caused by: java.io.IOException: Is a directory**
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:232)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:182)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:85)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:117)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:179)
	... 31 common frames omitted
	
	if i not use volume merge , i started fine 

### Expected behavior

start and keep data when start again

### Your installation details

docker compose

### Steps to reproduce

run docker compose

**Comment by MrAhmadHassan** [comment]
Hi @shipcake ,please assign this issue to me.
