### ISSUE TITLE
Amazon MSK (provisioned) cluster is Offline.

### ISSUE THREAD

**Issue by githubeto** [provectus/kafka-ui#4505]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

We are building MSK (Managed Streaming for Apache Kafka) and trying to connect to MSK from EKS (Elastic Kubernetes Service) pods using IRSA (IAM Roles for Service Accounts).
However, the cluster appears offline, and brokers and other elements are not displayed on the screen. Additionally, error logs are being output.

![image](https://github.com/user-attachments/assets/4febc7ae-0227-4e1f-bbe7-4e18fc11ddd1)

---

![image](https://github.com/user-attachments/assets/ee7891b1-738a-40cf-9c2d-38318571130f)

### Your installation details

App Version = v0.7.2 
Helm chart version = kafka-ui-0.7.6
Your application config : none.
Any IAAC configs : none.

### Steps to reproduce

1. 
```
helm upgrade --install -f kafka-ui-values.yaml kafka-ui kafka-ui/kafka-ui -n debezium
```
2. port-forward or create virtualservice(istio)

_kafka-ui-values.yaml_
```
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
serviceAccount: 
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxx:role/odc-stg-kafka-ui
  name: "kafka-ui"
ingress:
  enabled: false
envs:
  config:
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: b-1.xxxxxxxxxx.r31ee1.c2.kafka.ap-northeast-1.amazonaws.com:9092,b-2.xxxxxxxxxx.r31ee1.c2.kafka.ap-northeast-1.amazonaws.com:9092,b-3.xxxxxxxxxx.r31ee1.c2.kafka.ap-northeast-1.amazonaws.com:9092
    KAFKA_CLUSTERS_0_NAME: spdkube-stg-cdc-msk
    KAFKA_CLUSTERS_0_READONLY: "true"
    KAFKA_CLUSTERS_0_ZOOKEEPER: z-1.xxxxxxxxxx.r31ee1.c2.kafka.ap-northeast-1.amazonaws.com:2181,z-2.xxxxxxxxxx.r31ee1.c2.kafka.ap-northeast-1.amazonaws.com:2181,z-3.xxxxxxxxxx.r31ee1.c2.kafka.ap-northeast-1.amazonaws.com:2181
    KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
    KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: AWS_MSK_IAM
    KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'software.amazon.msk.auth.iam.IAMLoginModule required;'
    KAFKA_CLUSTERS_0_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS: 'software.amazon.msk.auth.iam.IAMClientCallbackHandler'
    LOGGING_LEVEL_ROOT: info
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi
```

### Logs

```
2024-11-22 11:24:48,175 ERROR [parallel-2] c.p.k.u.s.StatisticsService: Failed to collect cluster spdkube-stg-cdc-msk info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster spdkube-stg-cdc-msk
	at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$5(AdminClientServiceImpl.java:56)
	at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3783)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265)
	at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1886)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:340)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onError(MonoCacheTime.java:363)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
```

**Comment by mikebernich** [comment]
I am having the same issue 
org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
