### ISSUE TITLE
Support HTTPS connection

### ISSUE THREAD

**Issue by andormarkus** [provectus/kafka-ui#479]
### Is your proposal related to a problem?
In the current setup I don't see a configuration where I can supply SSL certificate and URL to switch connection to HTTPS.

For example in Airflow to change from HTTP to HTTPS I need to supply URL and certificates and rest is automated.
```yaml
AIRFLOW__WEBSERVER__BASE_URL: www.airflow.com/airflow
AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT: "/opt/airflow/secrets/ssl/tls.crt"
AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY: "/opt/airflow/secrets/ssl/tls.key"
```

**Comment by mac2000** [comment]
Here is how it can be done outside of docker:

Suppose we have: `fullchain.pem` and `privkey.pem` from LetsEncrypt

Pack them into keystore: `openssl pkcs12 -export -out keystore.jks -in fullchain.pem -inkey privkey.pem`

Now you may run kafka ui with `application.yml` like this one:

```yaml
server:
  port: 9090

  # this one is what you are looking for
  ssl:
    enabled: true
    key-store: file:path/to/keystore.jks
    key-store-password: kafka
    key-store-type: pkcs12
    key-password: 123456

auth:
  enabled: false
zookeeper:
  connection-timeout: 5000
kafka:
  admin-client-timeout: 30000
  clusters:
    - name: localhost:9092
      zookeeper: 127.0.0.1:2181
      bootstrapServers:localhost:9092
```

And if I remember correct any property can be overridden by corresponding environment variables

Locally I'm checking this by running: `java -Dspring.config.location=application.yml -jar kafka-ui-api-0.2.1.jar`

Everything works fine, I'm able to open UI with https

<details>
<summary>Only annoying exceptions are thrown non stop 🤷‍♂️</summary>


```logs
[id: 0x0d363742, L:/[0:0:0:0:0:0:0:1]:9090 ! R:/[0:0:0:0:0:0:0:1]:61553] onUncaughtException(SimpleConnection{channel=[id: 0x0d363742, L:/[0:0:0:0:0:0:0:1]:9090 ! R:/[0:0:0:0:0:0:0:1]:61553]})
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f6170692f636c7573746572732f6b61666b612d6c6f63616c2e7261626f74612e75612f737461747320485454502f312e310d0a486f73743a206c6f63616c686f73743a393039300d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a7365632d63682d75613a2022204e6f7420413b4272616e64223b763d223939222c20224368726f6d69756d223b763d223936222c2022476f6f676c65204368726f6d65223b763d223936220d0a7365632d63682d75612d6d6f62696c653a203f300d0a557365722d4167656e743a204d6f7a696c6c612f352e30202857696e646f7773204e542031302e303b2057696e36343b2078363429204170706c655765624b69742f3533372e333620284b48544d4c2c206c696b65204765636b6f29204368726f6d652f39362e302e343636342e313130205361666172692f3533372e33360d0a7365632d63682d75612d706c6174666f726d3a202257696e646f7773220d0a436f6e74656e742d547970653a206170706c69636174696f6e2f6a736f6e0d0a4163636570743a202a2f2a0d0a5365632d46657463682d536974653a2073616d652d6f726967696e0d0a5365632d46657463682d4d6f64653a20636f72730d0a5365632d46657463682d446573743a20656d7074790d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174652c2062720d0a4163636570742d4c616e67756167653a20656e2d55532c656e3b713d302e392c72753b713d302e382c756b3b713d302e370d0a436f6f6b69653a205f67613d4741312e312e323130393735393136312e313633373735343437323b205f67636c5f61753d312e312e313530303139313732332e313633373735343437383b205f686a53657373696f6e557365725f313931353135303d65794a705a434936496d4d325a446c6c5a6a4d354c5449354d574d744e5459314e6931684e3246694c57566b4f54466d596a637a597a466b5a534973496d4e795a5746305a5751694f6a45324d7a63334e5451304e7a49304e7a4573496d563461584e306157356e496a7030636e566c66513d3d3b2061695f757365723d626b3774327c323032312d31312d32375430383a31313a34322e3531375a3b2067726166616e615f73657373696f6e3d65396265613332343939373236373138613733646135336437353063623235340d0a0d0a
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f6170692f636c7573746572732f6b61666b612d6c6f63616c2e7261626f74612e75612f737461747320485454502f312e310d0a486f73743a206c6f63616c686f73743a393039300d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a7365632d63682d75613a2022204e6f7420413b4272616e64223b763d223939222c20224368726f6d69756d223b763d223936222c2022476f6f676c65204368726f6d65223b763d223936220d0a7365632d63682d75612d6d6f62696c653a203f300d0a557365722d4167656e743a204d6f7a696c6c612f352e30202857696e646f7773204e542031302e303b2057696e36343b2078363429204170706c655765624b69742f3533372e333620284b48544d4c2c206c696b65204765636b6f29204368726f6d652f39362e302e343636342e313130205361666172692f3533372e33360d0a7365632d63682d75612d706c6174666f726d3a202257696e646f7773220d0a436f6e74656e742d547970653a206170706c69636174696f6e2f6a736f6e0d0a4163636570743a202a2f2a0d0a5365632d46657463682d536974653a2073616d652d6f726967696e0d0a5365632d46657463682d4d6f64653a20636f72730d0a5365632d46657463682d446573743a20656d7074790d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174652c2062720d0a4163636570742d4c616e67756167653a20656e2d55532c656e3b713d302e392c72753b713d302e382c756b3b713d302e370d0a436f6f6b69653a205f67613d4741312e312e323130393735393136312e313633373735343437323b205f67636c5f61753d312e312e313530303139313732332e313633373735343437383b205f686a53657373696f6e557365725f313931353135303d65794a705a434936496d4d325a446c6c5a6a4d354c5449354d574d744e5459314e6931684e3246694c57566b4f54466d596a637a597a466b5a534973496d4e795a5746305a5751694f6a45324d7a63334e5451304e7a49304e7a4573496d563461584e306157356e496a7030636e566c66513d3d3b2061695f757365723d626b3774327c323032312d31312d32375430383a31313a34322e3531375a3b2067726166616e615f73657373696f6e3d65396265613332343939373236373138613733646135336437353063623235340d0a0d0a
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1198)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
        ... 17 more
```
</details>
