### ISSUE TITLE
Endless message loading

### ISSUE THREAD

**Issue by fee1good** [provectus/kafka-ui#583]
**Endless message loading**
If the messages don't found (I guess this is the reason) I got the infinity message loading page

**Steps to Reproduce**

1. Choose `Timestamp` under the `Seek Type` form
2. Choose the actual date
3. See the endless loading bar

**Expected behavior**
Page with empty search results

**Screenshots**
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/16759866/123237433-59daa500-d4e6-11eb-8fbd-e9f37e401035.png">

**Comment by iliax** [comment]
Backend returns 500 error response with "No offsets were found for requested timestamps" error msg. @germanosin don't you think we should just use latest offsets in this case?

**Comment by iliax** [comment]
Backend returns 500 error with "No offsets were found for requested timestamps" error message. @germanosin In case of not found offsets should we just return empty list or show error msg?

Anyway infinity message loading is UI bug -  in case of backend error we should stop loading and show error msg.
cc @workshur

**Comment by giom-l** [comment]
Hi, 

I also hit a similar issue but with different error message (still error 500 from backend)
Here is the error message I got 

```
Failed to parse record from topic <topic name>
```

**Comment by germanosin** [comment]
@giom-l , could you please provide stacktrace from logs?

**Comment by giom-l** [comment]
Yes, sure, here it is 

```
09:48:11.148 [boundedElastic-10] INFO  org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = earliest
	bootstrap.servers = [broker1:9092, broker2:9092, broker3:9092]
	check.crcs = true
	client.dns.lookup = default
	client.id = kafka-ui-8857146a-f8a0-4d5c-98f9-3e21ca8a5efd
	client.rack = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = null
	group.instance.id = null
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.BytesDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.BytesDeserializer

09:48:11.242 [boundedElastic-10] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka version: 2.4.0
09:48:11.242 [boundedElastic-10] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka commitId: 77a89fcf8d7fa018
09:48:11.242 [boundedElastic-10] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka startTimeMs: 1625737691242
09:48:11.245 [boundedElastic-10] INFO  com.provectus.kafka.ui.util.OffsetsSeek - Positioning consumer for topic LOGS-API-ACCESS-PREPROD-JSON with ConsumerPosition(seekType=BEGINNING, seekTo={}, seekDirection=FORWARD)
09:48:11.246 [boundedElastic-10] INFO  org.apache.kafka.clients.Metadata - [Consumer clientId=kafka-ui-8857146a-f8a0-4d5c-98f9-3e21ca8a5efd, groupId=null] Cluster ID: 2u1QvCEdQxCOrxdprxzvRA
09:48:11.252 [boundedElastic-10] INFO  org.apache.kafka.clients.consumer.KafkaConsumer - [Consumer clientId=kafka-ui-8857146a-f8a0-4d5c-98f9-3e21ca8a5efd, groupId=null] Subscribed to partition(s): LOGS-API-ACCESS-PREPROD-JSON-0, LOGS-API-ACCESS-PREPROD-JSON-1, LOGS-API-ACCESS-PREPROD-JSON-2
09:48:11.252 [boundedElastic-10] INFO  org.apache.kafka.clients.consumer.KafkaConsumer - [Consumer clientId=kafka-ui-8857146a-f8a0-4d5c-98f9-3e21ca8a5efd, groupId=null] Seeking to offset 0 for partition LOGS-API-ACCESS-PREPROD-JSON-0
09:48:11.252 [boundedElastic-10] INFO  org.apache.kafka.clients.consumer.KafkaConsumer - [Consumer clientId=kafka-ui-8857146a-f8a0-4d5c-98f9-3e21ca8a5efd, groupId=null] Seeking to offset 0 for partition LOGS-API-ACCESS-PREPROD-JSON-1
09:48:11.252 [boundedElastic-10] INFO  org.apache.kafka.clients.consumer.KafkaConsumer - [Consumer clientId=kafka-ui-8857146a-f8a0-4d5c-98f9-3e21ca8a5efd, groupId=null] Seeking to offset 0 for partition LOGS-API-ACCESS-PREPROD-JSON-2
09:48:11.252 [boundedElastic-10] INFO  com.provectus.kafka.ui.util.OffsetsSeek - Assignment: [LOGS-API-ACCESS-PREPROD-JSON-0, LOGS-API-ACCESS-PREPROD-JSON-1, LOGS-API-ACCESS-PREPROD-JSON-2]
09:48:11.275 [boundedElastic-10] INFO  com.provectus.kafka.ui.emitter.ForwardRecordEmitter - 500 records polled
09:48:11.279 [boundedElastic-10] ERROR org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler - [e532a29f]  500 Server Error for HTTP GET "/api/clusters/Kafka%20Logs/topics/LOGS-API-ACCESS-PREPROD-JSON/messages?limit=100"
java.lang.RuntimeException: Failed to parse record from topic LOGS-API-ACCESS-PREPROD-JSON
	at com.provectus.kafka.ui.serde.schemaregistry.SchemaRegistryRecordSerDe.deserialize(SchemaRegistryRecordSerDe.java:91) ~[classes!/:?]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.provectus.kafka.ui.controller.MessagesController#getTopicMessages(String, String, SeekType, List, Integer, String, SeekDirection, ServerWebExchange) [DispatcherHandler]
	|_ checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/api/clusters/Kafka%20Logs/topics/LOGS-API-ACCESS-PREPROD-JSON/messages?limit=100" [ExceptionHandlingWebHandler]
Stack trace:
		at com.provectus.kafka.ui.serde.schemaregistry.SchemaRegistryRecordSerDe.deserialize(SchemaRegistryRecordSerDe.java:91) ~[classes!/:?]
		at com.provectus.kafka.ui.util.ClusterUtil.mapToTopicMessage(ClusterUtil.java:218) ~[classes!/:?]
		at com.provectus.kafka.ui.service.ConsumingService.lambda$loadMessages$3(ConsumingService.java:71) ~[classes!/:?]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:199) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:151) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
		at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
		at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:34) [classes!/:?]
		at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:14) [classes!/:?]
		at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
		at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
		at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3283) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.provectus.kafka.ui.serde.schemaregistry.JsonMessageFormatter.parseJson(JsonMessageFormatter.java:26) ~[classes!/:?]
	at com.provectus.kafka.ui.serde.schemaregistry.JsonMessageFormatter.format(JsonMessageFormatter.java:22) ~[classes!/:?]
	at com.provectus.kafka.ui.serde.schemaregistry.SchemaRegistryRecordSerDe.deserialize(SchemaRegistryRecordSerDe.java:83) ~[classes!/:?]
	at com.provectus.kafka.ui.util.ClusterUtil.mapToTopicMessage(ClusterUtil.java:218) ~[classes!/:?]
	at com.provectus.kafka.ui.service.ConsumingService.lambda$loadMessages$3(ConsumingService.java:71) ~[classes!/:?]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:199) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:151) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:34) [classes!/:?]
	at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:14) [classes!/:?]
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
09:48:11.280 [boundedElastic-10] DEBUG org.springframework.http.codec.json.Jackson2JsonEncoder - [e532a29f] Encoding [class ErrorResponse {
    code: 5000
    message: Failed to parse record from topic LOGS-API-AC (truncated)...]

```

**Comment by giom-l** [comment]
My issue seems very linked to #644 
Also, I tried to switch back to latest stable (`v0.1.0(1869a7f)`) and it worked like a charm (unless I haven't the ability to browse messages backward anymore)
