### ISSUE TITLE
Messages section for Topic  is throwing 500

### ISSUE THREAD

**Issue by sreenivasvp** [provectus/kafka-ui#644]
**Describe the bug**
(A clear and concise description of what the bug is.)

Request :
/api/clusters/ENV-Test/topics/configuration-service/messages?limit=100
Response :
{"code":5000,"message":"Failed to parse record from topic configuration-service","timestamp":1625668145100,"requestId":"2c1db961","fieldsErrors":null}

**Set up**
(How do you run the app?)

**Steps to Reproduce**

Select a topic and check for messages
Throws 500

**Expected behavior**
(A clear and concise description of what you expected to happen)

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by germanosin** [comment]
Hi, @sreenivasvp. Thanks for creating this issue. Could you please provide stacktrace from logs?

**Comment by sreenivasvp** [comment]
@germanosin 

14:30:16.589 [boundedElastic-5] ERROR org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler - [2c1db961]  500 Server Error for HTTP GET "/api/clusters/Env-Test/topics/configuration-service-inbound/messages?limit=100"
java.lang.RuntimeException: Failed to parse record from topic configuration-service-inbound
        at com.provectus.kafka.ui.serde.schemaregistry.SchemaRegistryRecordSerDe.deserialize(SchemaRegistryRecordSerDe.java:91) ~[classes!/:?]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ Handler com.provectus.kafka.ui.controller.MessagesController#getTopicMessages(String, String, SeekType, List, Integer, String, SeekDirection, ServerWebExchange) [DispatcherHandler]
        |_ checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        |_ checkpoint ⇢ HTTP GET "/api/clusters/Env-Test/topics/configuration-service-inbound/messages?limit=100" [ExceptionHandlingWebHandler]
Stack trace:
                at com.provectus.kafka.ui.serde.schemaregistry.SchemaRegistryRecordSerDe.deserialize(SchemaRegistryRecordSerDe.java:91) ~[classes!/:?]
                at com.provectus.kafka.ui.util.ClusterUtil.mapToTopicMessage(ClusterUtil.java:218) ~[classes!/:?]
                at com.provectus.kafka.ui.service.ConsumingService.lambda$loadMessages$3(ConsumingService.java:71) ~[classes!/:?]
                at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:199) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
                at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:151) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
                at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
                at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:34) [classes!/:?]
                at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:14) [classes!/:?]
                at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
                at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
                at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
                at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('c' (code 99)): Expected space separating root-level values
 at [Source: (byte[])"6971cafd-591c-47fd-97dd-3d1e66cd31e0"; line: 1, column: 6]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840) ~[jackson-core-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712) ~[jackson-core-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637) ~[jackson-core-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:684) ~[jackson-core-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._verifyRootSpace(UTF8StreamJsonParser.java:1659) ~[jackson-core-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parsePosNumber(UTF8StreamJsonParser.java:1399) ~[jackson-core-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:854) ~[jackson-core-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:753) ~[jackson-core-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4340) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3283) ~[jackson-databind-2.10.2.jar!/:2.10.2]
        at com.provectus.kafka.ui.serde.schemaregistry.JsonMessageFormatter.parseJson(JsonMessageFormatter.java:26) ~[classes!/:?]
        at com.provectus.kafka.ui.serde.schemaregistry.JsonMessageFormatter.format(JsonMessageFormatter.java:22) ~[classes!/:?]
        at com.provectus.kafka.ui.serde.schemaregistry.SchemaRegistryRecordSerDe.deserialize(SchemaRegistryRecordSerDe.java:83) ~[classes!/:?]
        at com.provectus.kafka.ui.util.ClusterUtil.mapToTopicMessage(ClusterUtil.java:218) ~[classes!/:?]
        at com.provectus.kafka.ui.service.ConsumingService.lambda$loadMessages$3(ConsumingService.java:71) ~[classes!/:?]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:199) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:151) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
        at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
        at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:34) [classes!/:?]
        at com.provectus.kafka.ui.emitter.ForwardRecordEmitter.accept(ForwardRecordEmitter.java:14) [classes!/:?]
        at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
14:30:16.591 [boundedElastic-5] DEBUG org.springframework.http.codec.json.Jackson2JsonEncoder - [2c1db961] Encoding [class ErrorResponse {
    code: 5000
    message: Failed to parse record from topic configuration-se (truncated)...]

**Comment by germanosin** [comment]
@sreenivasvp this is really helpful! We'll return to you asap.

**Comment by Haarolean** [comment]
I couldn't reproduce the issue on latest master (587e08ab01032bdcc76058a1e217c0d31aeca648), messages are present. it might have been fixed lately.

![image](https://user-images.githubusercontent.com/1494347/125604046-148240f9-496e-4388-9d62-868eb88f554e.png)

@sreenivasvp let us know if you encounter this again.
