### ISSUE TITLE
[bug] UI shows "no messages found" when it is unable to connect to schema registry

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#979]
**Describe the bug**
(A clear and concise description of what the bug is.)

**Set up**
(How do you run the app?)

**Steps to Reproduce**

1. Avro encoded messages in topic
2. Schema published to SR
3. UI unable to connect to SR because of https://github.com/provectus/kafka-ui/issues/886#issuecomment-927707688 (when is this going to be fixed tho?)
4. ...
5. profit

**Expected behavior**
See messages undecoded. Maybe in hex format, or better representation of bytes.

**Actual behavior**
Shows "no messages found", while on the same page it clearly shows there are messages in the topic (see screenshot).

**Screenshots**
![Screenshot from 2021-10-18 16-32-10](https://user-images.githubusercontent.com/985805/137696768-b65f7ec4-c5bf-444a-980c-39d40bd3f1c8.png)

**Log**

```
08:33:05.235 [elastic-10] WARN  com.provectus.kafka.ui.serde.schemaregistry.SchemaRegistryAwareRecordSerDe - Failed to get Schema for topic REDACTED
java.net.SocketTimeoutException: Connect timed out
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
```

**Comment by akamensky** [comment]
#886 is fixed with "split by comma and use first element" instead of proper failover, but regardless of that -- this issue still stands as the messages are actually there and could be read.

**Comment by Haarolean** [comment]
Are there any failed requests on UI side in network tab?
