### ISSUE TITLE
kafka-ui doesn't start: Error creating bean with name 'clusterService' defined in URL

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [provectus/kafka-ui#981]
**Describe the bug**

Kafka-ui doesn't start, it throws this error in logs:
```
11:23:37.946 [main] INFO  org.springframework.core.KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.

  _  __      __ _               _   _ ___
 | |/ /__ _ / _| | ____ _      | | | |_ _|
 | ' // _` | |_| |/ / _` |_____| | | || |
 | . \ (_| |  _|   < (_| |_____| |_| || |
 |_|\_\__,_|_| |_|\_\__,_|      \___/|___|


11:23:39.205 [main] INFO  com.provectus.kafka.ui.KafkaUiApplication - Starting KafkaUiApplication on kafka-ui-5ff7bf5bd8-7264s with PID 1 (/kafka-ui-api.jar started by root in /)
11:23:39.206 [main] DEBUG com.provectus.kafka.ui.KafkaUiApplication - Running with Spring Boot v2.2.4.RELEASE, Spring v5.2.3.RELEASE
11:23:39.207 [main] INFO  com.provectus.kafka.ui.KafkaUiApplication - No active profile set, falling back to default profiles: default
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/kafka-ui-api.jar!/BOOT-INF/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/kafka-ui-api.jar!/BOOT-INF/lib/log4j-slf4j-impl-2.12.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (reactor.util.Loggers$LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
11:23:42.962 [main] INFO  org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration -

Using generated security password: eecd6f9b-14c5-418d-81f6-7b318cfcdc94

11:23:43.062 [main] WARN  org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JodaDateTimeJacksonConfiguration - Auto-configuration of Jackson's Joda-Time integration is deprecated in favor of using java.time (JSR-310).
11:23:43.430 [main] WARN  org.springframework.http.converter.json.Jackson2ObjectMapperBuilder - For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
11:23:43.584 [main] WARN  org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clusterService' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/service/ClusterService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clustersStorage': Invocation of init method failed; nested exception is java.lang.NullPointerException
11:23:43.630 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
11:23:43.633 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clusterService' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/service/ClusterService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clustersStorage': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at com.provectus.kafka.ui.KafkaUiApplication.main(KafkaUiApplication.java:14) [classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [kafka-ui-api.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [kafka-ui-api.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [kafka-ui-api.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [kafka-ui-api.jar:?
```

**Set up**
I installed kafka-ui with Helm Chart on kubernetes (v1.20.11):

```
$ export HELM_APP=kafka-ui
$ export HELM_REPO=https://provectus.github.io/kafka-ui
$ helm repo add ${HELM_APP} ${HELM_REPO}
$ helm upgrade ${HELM_APP} ${HELM_APP}/${HELM_APP} --namespace=kafka-ui --install --set envs.config.KAFKA_CLUSTER_0_NAME=kafka0 --set envs.config.KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka0-kafka-bootstrap.kafka-cluster.svc.cluster.local:9092 --set envs.config.KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SSL
```

**Steps to Reproduce**
Nothing besides steps described above.

**Expected behavior**
I expect kafka-ui to start correctly or write clear error message.

**Comment by mateuszkwiatkowski** [comment]
Hi @Haarolean, 
Thank you for prompt response. The image spec specify :latest tag:
```
    image: provectuslabs/kafka-ui:latest
    imagePullPolicy: IfNotPresent
```

Checking pod status I see this sha256 sum:
```
    imageID: docker-pullable://provectuslabs/kafka-ui@sha256:9c47ee10c05ae9e25802b6f3c9478ebbfaee7c1c9cf3bd6d7d9a99b270bc7f80
```

Which translates to this image, tagged 15 days ago: https://hub.docker.com/layers/provectuslabs/kafka-ui/latest/images/sha256-9c47ee10c05ae9e25802b6f3c9478ebbfaee7c1c9cf3bd6d7d9a99b270bc7f80?context=explore

**Comment by mateuszkwiatkowski** [comment]
@Haarolean It seems that this problem is now fixed. Thank you so much for prompt fix!

**Comment by Haarolean** [comment]
That’s great, glad to hear.
