### ISSUE TITLE
Zookeeper status is offline

### ISSUE THREAD

**Issue by vipinvijay7793** [provectus/kafka-ui#982]
Hello,

zookeeper status showing as offline. I have added the config I have done in my installation please guide me if I missed anything or let me know if the feature is not available.
![image](https://user-images.githubusercontent.com/67056867/137731100-3f24132d-6ec6-4e50-9915-e2b491f9417d.png)

please see the config I have done for docker composer
![image](https://user-images.githubusercontent.com/67056867/137736389-b3a913d4-a171-4ec5-ba92-3e94a4f29615.png)

@germanosin can you please guide me on this issue

**Comment by Haarolean** [comment]
Hi, please share your container logs. There might be some errors for ZookeeperService.

**Comment by namgk** [comment]
I'm having the same problem, here's the log. My zookeeper client listened at 2181

```
05:38:54.851 [kafka-admin-client-thread | adminclient-1] DEBUG com.provectus.kafka.ui.service.ZookeeperService - Start getting Zookeeper metrics for kafkaCluster: local
05:38:54.952 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.service.ZookeeperService - A zookeeper exception has occurred
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /brokers/ids
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102) ~[zookeeper-3.5.7.jar!/:3.5.7]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[zookeeper-3.5.7.jar!/:3.5.7]
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2589) ~[zookeeper-3.5.7.jar!/:3.5.7]
	at com.provectus.kafka.ui.service.ZookeeperService.isZkClientConnected(ZookeeperService.java:37) ~[classes!/:?]
	at com.provectus.kafka.ui.service.ZookeeperService.isZookeeperOnline(ZookeeperService.java:29) ~[classes!/:?]
	at com.provectus.kafka.ui.service.KafkaService.buildFromData(KafkaService.java:174) ~[classes!/:?]
	at com.provectus.kafka.ui.service.KafkaService.lambda$getUpdatedCluster$3(KafkaService.java:142) ~[classes!/:?]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at com.provectus.kafka.ui.util.ClusterUtil.lambda$toMono$0(ClusterUtil.java:64) ~[classes!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl$WhenCompleteBiConsumer.accept(KafkaFutureImpl.java:177) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl$WhenCompleteBiConsumer.accept(KafkaFutureImpl.java:162) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl.complete(KafkaFutureImpl.java:221) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl$Applicant.accept(KafkaFutureImpl.java:65) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl$Applicant.accept(KafkaFutureImpl.java:49) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl.complete(KafkaFutureImpl.java:221) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl$Applicant.accept(KafkaFutureImpl.java:65) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl$Applicant.accept(KafkaFutureImpl.java:49) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl.complete(KafkaFutureImpl.java:221) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.KafkaFuture$AllOfAdapter.maybeComplete(KafkaFuture.java:82) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.KafkaFuture$AllOfAdapter.accept(KafkaFuture.java:76) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.KafkaFuture$AllOfAdapter.accept(KafkaFuture.java:57) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl.complete(KafkaFutureImpl.java:221) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.clients.admin.KafkaAdminClient$13.handleResponse(KafkaAdminClient.java:2423) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.handleResponses(KafkaAdminClient.java:1189) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1341) [kafka-clients-2.8.0.jar!/:?]
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1264) [kafka-clients-2.8.0.jar!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Haarolean** [comment]
Hey @namgk, thanks for reaching out. Please share some details:
1. How do you run kafka-ui itself? 
2. How do you run zookeeper? Which version?
3. Does it happen all the time or does it work sometimes?

**Comment by linuxmail** [comment]
Hello,

I have the same issue, but it might be related to the my SSL/TLS and auth config. I'm  new to Zoo and Kafka ..

My (Puppet) config looks like:

```yaml
...
      - KAFKA_CLUSTERS_0_NAME=FRA_TEST
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=fra-test-kafka-01.example.local:9093,fra-test-kafka-02.example.local:9093,fra-test-kafka-03.example.local:9093,fra-test-kafka-04.example.local:9093,fra-test-kafka-05.example.local:9093
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SSL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=\"org.apache.kafka.common.security.plain.PlainLoginModule required username=\'admin\' password=\'admin-secret\';\"
      - KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/certs/local_chain.pem
      - KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE=PEM

      - KAFKA_CLUSTERS_0_ZOOKEEPER: 'fra-test-zoo-01.example.local:2281,fra-test-zoo-02.example.local:2281,fra-test-zoo-03.example.local:2281'
      - KAFKA_CLUSTERS_0_ZOOKEEPER_CLIENTCNXNSOCKET: 'org.apache.zookeeper.ClientCnxnSocketNetty'
      - KAFKA_CLUSTERS_0_ZOOKEEPER_CLIENT_SECURE: true
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
      - KAFKA_CLUSTERS_0_ZOOKEEPER_SSL_KEYSTORE_LOCATION: '/certs/local_chain.pem'
...
```
While the Kafka part works .. Zookeeper does not.

* Zookeeper config (zoo.cfg):

```
root@fra-test-zoo-01:[~]: grep -i -E   '(auth|ssl)'  /etc/zookeeper/conf/zoo.cfg 

# Enable SASL authentication and use the default provider/renew provided by cloudera
authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
ssl.protocol=TLSv1.2
ssl.hostnameVerification=false
ssl.keyStore.location=/etc/ssl/private/local_chain.crt
ssl.keyStore.type=PEM
ssl.trustStore.location=/etc/ssl/certs/ca-certificates.crt
ssl.trustStore.type=PEM
sslQuorum=true
ssl.quorum.protocol=TLSv1.2
ssl.quorum.hostnameVerification=false
ssl.quorum.keyStore.location=/etc/ssl/private/local_chain.crt
ssl.quorum.keyStore.type=PEM
ssl.quorum.trustStore.type=PEM
ssl.quorum.trustStore.location=/etc/ssl/certs/ca-certificates.crt
ssl.clientAuth=none
```
* Jaas config

```
root@fra-test-zoo-01:[~]: cat /etc/zookeeper/conf/jaas.conf 
Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
        user_super="admin-secret"
        user_kafka="kafka-secret"
    ;
};
```
So question would be .. what is wrong :-)

cu denny

**Comment by namgk** [comment]
It happens all the time.

It's a bit tricky with me I suppose.

I'm running a k8s cluster of Kafka using Strimzi, it spawned both zookeeper and kafka, all plain text. There's a super quick quick-start here (https://strimzi.io/quickstarts/). Kafka-ui is also a pod in the cluster. I believe it's zookeeper 3.6.3. 

So far everything seems to work (e.g. topics, producers, consumers, schema registry), so I doubt that it's anything related to the connectivity issue.

**Comment by Haarolean** [comment]
@linuxmail We have an example for configuring [ssl enabled zookeeper](https://github.com/provectus/kafka-ui/blob/master/docker/kafka-ui-zookeeper-ssl.yml)

@linuxmail @namgk could you folks check this out: does it work right after container (kafka-ui) start? I wanna know if this is related in any way to connection expiration. Does the first connect attempt fails as well?

**Comment by linuxmail** [comment]
Hello @Haarolean 

does it also support PAM? Because we do not have the JKS.

**Comment by Haarolean** [comment]
> Hello @Haarolean
> 
> does it also support PAM? Because we do not have the JKS. I've found the SSL config .. and used it .. but it failed .. and also auth is required, with DIGEST :-)

I don't have any other working example with zookeeper, all we've got is located in `docker` directory, so I can neither confirm nor deny this, sorry.

**Comment by Bagmetalex** [comment]
I found the following article on your problem,
https://stackoverflow.com/questions/35125579/kafka-to-zookeeper-command-produces-error
 It seemed to help me, but I see it in the logs
15:00:43.729 [kafka-admin-client-thread | adminclient-1] DEBUG com.provectus.kafka.ui.service.ZookeeperService - Start getting Zookeeper metrics for kafkaCluster: kafka_development
and zookeeper offline status :(

**Comment by Haarolean** [comment]
@Bagmetalex are there any errors in your case or just these messages?
Could you share details about your setup as well?

**Comment by Bagmetalex** [comment]
```
docker run --rm -p 8080:8080 --name kafka-ui -d \
-e KAFKA_CLUSTERS_0_NAME=kafka_development \
-e KAFKA_CLUSTERS_0_ZOOKEEPER=kafkadev3:2181,kafkadev2:2181,kafkadev:2181/kafka_development \
-e KAFKA_CLUSTERS_0_ZOOKEEPER_CLIENTCNXNSOCKET=org.apache.zookeeper.ClientCnxnSocketNetty \
-e KAFKA_CLUSTERS_0_ZOOKEEPER_CLIENT_SECURE=true \
-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafkadev3:9093,kafkadev2:9093,kafkadev:9093 \
-e KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT \
-e KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-256 \
-e "KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username=login' password='pass';" \
docker-hub.binary.alfabank.ru/provectuslabs/kafka-ui:0.2.1
```

**Comment by Haarolean** [comment]
@Bagmetalex thanks. Is there any specific reason why you have applied this solution just for one of the zookeepers (kafkadev)? Do others work fine? if that's the case, is there any difference between these zookeeper instances?

**Comment by Bagmetalex** [comment]
no zookeeper version is the same on all hosts 3.4.10
I applied this value by analogy with kafka-manager
`zk1:2181,zk2:2181,zk3:2181/NAMESPACE`
If I specify
`kafkadev3:2181/kafka_development,kafkadev2:2181/kafka_development,kafkadev:2181/kafka_development`
I get errors as indicated at the beginning of the issuse

**Comment by Haarolean** [comment]
That's enough, thanks. I'll take a look this week, your setup seems a bit easier than the others.

**Comment by Bagmetalex** [comment]
Hi guys, I do not know why, but my zookeeper status has online
```
 docker run --rm \
 --name kafka_ui -d \
 -p 8080:8080 \
 -e KAFKA_CLUSTERS_0_NAME=kafka_development \
 -e KAFKA_CLUSTERS_0_ZOOKEEPER=kafkadev3:2181,kafkadev2:2181,kafkadev:2181/kafka_development \
 -e KAFKA_CLUSTERS_0_ZOOKEEPER_CLIENTCNXNSOCKET=org.apache.zookeeper.ClientCnxnSocketNetty \
 -e KAFKA_CLUSTERS_0_ZOOKEEPER_CLIENT_SECURE=true \
 -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafkadev3:9093,kafkadev2:9093,kafkadev:9093 \
 -e KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT \
 -e KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-256 \
 -e "KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username=login password=pass;" \
provectuslabs/kafka-ui:0.2.1
```
in logs i see

```
10:39:06.767 [parallel-1] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: kafka_development
10:39:06.824 [kafka-admin-client-thread | adminclient-1] DEBUG com.provectus.kafka.ui.service.ZookeeperService - Start getting Zookeeper metrics for kafkaCluster: kafka_development
10:39:08.521 [boundedElastic-4] DEBUG org.springframework.http.codec.json.Jackson2JsonEncoder - [137ae259] Encoding [class ClusterStats {
    brokerCount: 3
    zooKeeperStatus: 1
    activeControllers: 1
    onlinePa (truncated)...]
10:39:13.520 [boundedElastic-4] DEBUG org.springframework.http.codec.json.Jackson2JsonEncoder - [137ae259] Encoding [class ClusterStats {
    brokerCount: 3
    zooKeeperStatus: 1
    activeControllers: 1
    onlinePa (truncated)...]
10:39:18.520 [boundedElastic-4] DEBUG org.springframework.http.codec.json.Jackson2JsonEncoder - [137ae259] Encoding [class ClusterStats {
    brokerCount: 3
    zooKeeperStatus: 1
    activeControllers: 1
    onlinePa (truncated)...]
```
